// СГЕНЕРИРОВАНО scripts/gen_lang.py из editor/lang/ru.json — не править руками.
// Правки вносятся в JSON, затем: python3 scripts/gen_lang.py
//
// Язык: Русский. Строк: 1087.
struct TranslationPair {
    const char* Key;
    const char* Value;
};

constexpr TranslationPair kRussianStrings[] = {
    {"\nCtrl+Z undoes this.",
     "\nОтменить можно через Ctrl+Z."},
    {"\nTogether with its children that is ",
     "\nВместе с потомками это "},
    {"   ·   the folder is gone",
     "   ·   папки больше нет"},
    {"  (off)",
     "  (выключена)"},
    {" (with maps)",
     " (с картами)"},
    {" and ",
     " и ещё "},
    {" companion file(s))",
     " спутник(ов))"},
    {" d ago",
     " дн назад"},
    {" entities.",
     " сущностей."},
    {" h ago",
     " ч назад"},
    {" mo ago",
     " мес назад"},
    {" — details in Console",
     " — подробности в Console"},
    {"%.1f GiB",
     "%.1f ГиБ"},
    {"%.1f KiB",
     "%.1f КиБ"},
    {"%.1f MiB",
     "%.1f МиБ"},
    {"%llu B",
     "%llu Б"},
    {"%s -> %s (%.1fx smaller)",
     "%s -> %s (%.1fx меньше)"},
    {"%zu selected — editing the primary one",
     "Выбрано %zu — правим первичный"},
    {"(no event)",
     "(событие не задано)"},
    {"(no light entities)",
     "(источников-сущностей нет)"},
    {"(no scenes yet)",
     "(сцен пока нет)"},
    {"(none)",
     "(нет)"},
    {"(open a project to save)",
     "(откройте проект, чтобы сохранить)"},
    {"(or the file cannot be read — details in Console).",
     "(или файл не читается — подробности в Console)."},
    {"0 — smooth; >0 — snap to the step",
     "0 — плавно; больше нуля — прилипать к шагу"},
    {"0 — stretch to fit; >0 — source pixel size",
     "0 — растянуть по размеру; >0 — размер пикселя исходника"},
    {"1 — a flat backdrop instead of the game frame;\n0 — design the HUD over the game.",
     "1 — ровный фон вместо игрового кадра;\n0 — верстать худ поверх игры."},
    {"1:1",
     "1:1"},
    {"2 = analytic two-bone, more = FABRIK",
     "2 — аналитическое решение на две кости, больше — FABRIK"},
    {"9-slice (l,t,r,b)",
     "9-срез (л,в,п,н)"},
    {"9-slice l,t,r,b",
     "Девять частей: слева, сверху, справа, снизу"},
    {"; not found: ",
     "; не найдено: "},
    {"A UI root: reference resolution and order between roots",
     "Корень интерфейса: опорное разрешение и порядок между корнями"},
    {"A caption: size, colour, alignment, wrapping",
     "Надпись: размер, цвет, выравнивание, перенос"},
    {"A file on disk — the change affects EVERY object using this material.",
     "Файл на диске — изменится у ВСЕХ объектов с этим материалом."},
    {"A file with this name already exists",
     "Файл с таким именем уже есть"},
    {"A file, a piece of a sprite sheet, 9-slice, pixel art",
     "Файл, кусок атласа, 9-срез, пиксель-арт"},
    {"A modular 3D engine: ECS, RHI, PBR, physics, scripting, UI.",
     "Модульный 3D-движок: ECS, RHI, PBR, физика, скриптинг, UI."},
    {"A name cannot contain / \\ : * ? \" < > |",
     "В имени нельзя использовать / \\ : * ? \" < > |"},
    {"A point light at the object's position. Its shadow costs six passes of geometry (one per cube face), so it is best left only to the lamps that have something to occlude.",
     "Точечный свет в позиции объекта. Тень стоит шести проходов геометрии (по грани куба), поэтому её лучше оставлять только тем лампам, у которых есть что затенять."},
    {"A project keeps scenes, assets and materials in one folder.",
     "Проект хранит сцены, ассеты и материалы в одной папке."},
    {"A slider or a checkbox",
     "Ползунок или галка"},
    {"A subtree template: double-clicking in Assets places a copy into the scene.",
     "Заготовка-поддерево: двойной клик в Assets ставит копию в сцену."},
    {"A vector icon of the engine",
     "Векторный значок движка"},
    {"AO Radius",
     "Радиус AO"},
    {"AO Strength",
     "Сила AO"},
    {"About SAGE",
     "О SAGE"},
    {"About SAGE...",
     "О SAGE…"},
    {"Accent colour",
     "Цвет акцента"},
    {"Across",
     "По горизонтали"},
    {"Action",
     "Действие"},
    {"Active",
     "Активен"},
    {"Add Component",
     "Добавить компонент"},
    {"Add Goal",
     "Добавить цель"},
    {"Add Part",
     "Добавить часть"},
    {"Add an interface element",
     "Добавить элемент интерфейса"},
    {"Add link",
     "Добавить связь"},
    {"Add the prefab as a child",
     "Добавить префаб дочерним объектом"},
    {"Add variable",
     "Добавить переменную"},
    {"Add via Entity > Create Light; type/params in Inspector",
     "Добавляется через Entity > Create Light; тип и параметры — в инспекторе"},
    {"Added to the material emissive. Above 1 gives a bloom halo.",
     "Прибавляется к свечению материала. Больше 1 — ореол (bloom)."},
    {"Added to the scene: ",
     "Добавлено в сцену: "},
    {"Aim (look-at)",
     "Прицеливание (взгляд на цель)"},
    {"Aim Axis",
     "Ось прицеливания"},
    {"Air",
     "Воздух"},
    {"Albedo",
     "Альбедо"},
    {"Align",
     "Выравнивание"},
    {"Align Normal",
     "Выровнять по нормали"},
    {"Align the selection to the primary object",
     "Выровнять выделенные по первичному"},
    {"Align to axis",
     "Выровнять по оси"},
    {"Aligned along axis ",
     "Выровнено по оси "},
    {"Aligned to the last clicked element",
     "Равняются по последнему выделенному"},
    {"All at once (T): move + rotate + scale",
     "Всё сразу (T): перенос + поворот + масштаб"},
    {"All components already added",
     "Все компоненты уже добавлены"},
    {"All files",
     "Все файлы"},
    {"All panels are closed",
     "Все панели закрыты"},
    {"Alpha",
     "Прозрачность"},
    {"Alpha and input for the whole subtree",
     "Прозрачность и ввод для всего поддерева"},
    {"Ambient (hemisphere)",
     "Засветка (полусфера)"},
    {"Ambient Occlusion",
     "Затенение складок (AO)"},
    {"Ambient Occlusion (SSAO)",
     "Затенение складок (SSAO)"},
    {"Ambient occlusion, channel R. Empty means AO = 1.",
     "Ambient occlusion, канал R. Пусто — AO = 1."},
    {"Anchor",
     "Привязка"},
    {"Anchor (offset)",
     "Привязка (смещение)"},
    {"Angle Limit",
     "Предельный угол"},
    {"Animated Model",
     "Анимированная модель"},
    {"Animation",
     "Анимация"},
    {"Appearance",
     "Оформление"},
    {"Applied on top of the material.",
     "Накладываются поверх материала."},
    {"Apply a preset...",
     "Применить заготовку…"},
    {"Argument",
     "Аргумент"},
    {"Aspect Ratio",
     "Соотношение сторон"},
    {"Asset",
     "Ассет"},
    {"Assets",
     "Ассеты"},
    {"Assets -> Import...",
     "Assets -> Импорт…"},
    {"Assign the material to this object",
     "Назначить материал этому объекту"},
    {"Atlas size",
     "Размер атласа"},
    {"Attach the script to this object",
     "Прикрепить скрипт к этому объекту"},
    {"Auto Width",
     "Ширина автоматически"},
    {"Auto-scroll",
     "Автопрокрутка"},
    {"Average",
     "Усреднять"},
    {"Axis",
     "Ось"},
    {"Azimuth",
     "Азимут"},
    {"Backdrop",
     "Подложка"},
    {"Background, rounding, border, gradient, shadow",
     "Фон, скругление, рамка, градиент, тень"},
    {"Bake GI",
     "Запечь GI"},
    {"Bake Probe",
     "Снять зонд"},
    {"Baked into the mesh on load — affects editor and built game",
     "Запекается в меш при загрузке — влияет и на редактор, и на собранную игру"},
    {"Baked: %d entities, %d page(s), probes %dx%dx%d",
     "Запечено: сущностей %d, страниц %d, проб %dx%dx%d"},
    {"Bakes indirect light to lightmaps (static) and a probe",
     "Запекает непрямой свет в лайтмапы (для статики) и в объём проб"},
    {"Bar",
     "Полоса"},
    {"Base colour. Multiplied by the Albedo above.",
     "Базовый цвет. Умножается на Albedo выше."},
    {"Blend Time",
     "Время перехода"},
    {"Block raycasts",
     "Ловить клики"},
    {"Bloom",
     "Ореол (bloom)"},
    {"Bloom Intensity",
     "Сила ореола"},
    {"Bloom Threshold",
     "Порог ореола"},
    {"Body Type",
     "Тип тела"},
    {"Bone",
     "Кость"},
    {"Bones reach for a target",
     "Кости тянутся к цели"},
    {"Border",
     "Рамка"},
    {"Border Color",
     "Цвет рамки"},
    {"Border colour",
     "Цвет рамки"},
    {"Border thickness",
     "Толщина рамки"},
    {"Border width",
     "Толщина рамки"},
    {"Borderless",
     "Без рамки"},
    {"Both",
     "Обе оси"},
    {"Bottom Center",
     "Снизу по центру"},
    {"Bottom Left",
     "Слева снизу"},
    {"Bottom Right",
     "Справа снизу"},
    {"Bottom center",
     "По центру снизу"},
    {"Bottom edges",
     "По нижнему краю"},
    {"Bottom left",
     "Слева снизу"},
    {"Bottom right",
     "Справа снизу"},
    {"Bottom to top",
     "Снизу вверх"},
    {"Bounces",
     "Переотражений"},
    {"Bounds of the selection",
     "Габариты выделенного"},
    {"Box",
     "Коробка"},
    {"Box Half Extents",
     "Полуразмеры коробки"},
    {"Box Parallax",
     "Поправка на коробку"},
    {"Brighter on hover",
     "Ярче под курсором"},
    {"Bring a file into the project",
     "Внести файл в проект"},
    {"Bring back on screen",
     "Вернуть на экран"},
    {"Bring forward",
     "Выше соседей"},
    {"Broken references: ",
     "Битых ссылок: "},
    {"Brought in: ",
     "Внесено: "},
    {"Brought into the project: ",
     "Внесено в проект: "},
    {"Browse",
     "Обзор"},
    {"Browse...",
     "Обзор…"},
    {"Build",
     "Собрать"},
    {"Build Game",
     "Сборка игры"},
    {"Build Game...",
     "Собрать игру…"},
    {"Built: %s",
     "Собрано: %s"},
    {"Burst Count",
     "Частиц в залпе"},
    {"Burst Interval",
     "Интервал залпов"},
    {"Button",
     "Кнопка"},
    {"CPU, ms",
     "CPU, мс"},
    {"Call on object",
     "Позвать у объекта"},
    {"Camera",
     "Камера"},
    {"Camera inside this box uses this probe",
     "Камера внутри этой коробки использует этот зонд"},
    {"Camera, light and ready-made interface screens",
     "Камера, свет и готовые экраны интерфейса"},
    {"Cancel",
     "Отмена"},
    {"Canvas",
     "Холст"},
    {"Canvas zoom (wheel over the canvas)",
     "Масштаб холста (колесо над холстом)"},
    {"Capsule",
     "Капсула"},
    {"Captures the scene around this point into a cubemap",
     "Снимает окружение вокруг этой точки в кубическую карту"},
    {"Captures the surroundings for reflections",
     "Снимает окружение для отражений"},
    {"Casts shadows",
     "Отбрасывает тени"},
    {"Catches the mouse",
     "Ловит мышь"},
    {"Center",
     "По центру"},
    {"Center Left",
     "Слева по центру"},
    {"Center Right",
     "Справа по центру"},
    {"Center Text",
     "Текст по центру"},
    {"Center left",
     "Слева по центру"},
    {"Center right",
     "Справа по центру"},
    {"Centers",
     "Центры"},
    {"Centers horizontally",
     "По центру, по горизонтали"},
    {"Centers vertically",
     "По центру, по вертикали"},
    {"Chain Length",
     "Длина цепочки"},
    {"Channel R. Multiplied by the Metallic factor above.",
     "Канал R. Умножается на фактор Metallic выше."},
    {"Channel R. Multiplied by the Roughness factor above.",
     "Канал R. Умножается на фактор Roughness выше."},
    {"Character Controller",
     "Контроллер персонажа"},
    {"Checkbox",
     "Галочка"},
    {"Choose a folder",
     "Выберите папку"},
    {"Choose a material",
     "Выбрать материал"},
    {"Choose a model",
     "Выбрать модель"},
    {"Choose a script",
     "Выбрать скрипт"},
    {"Choose an image",
     "Выбрать картинку"},
    {"Choose folder",
     "Выбрать папку"},
    {"Clear",
     "Очистить"},
    {"Clear bake",
     "Стереть запечённое"},
    {"Clear the console",
     "Очистить консоль"},
    {"Click — show in Assets",
     "Клик — показать в Assets"},
    {"Clip Children",
     "Обрезать детей"},
    {"Close",
     "Закрыть"},
    {"Cloud Bottom",
     "Низ облаков"},
    {"Cloud Density",
     "Плотность облаков"},
    {"Cloud Steps",
     "Шагов сквозь облака"},
    {"Cloud Top",
     "Верх облаков"},
    {"Clouds",
     "Облака"},
    {"Code",
     "Код"},
    {"Collapse",
     "Свернуть повторы"},
    {"Collapse the tools",
     "Свернуть инструменты"},
    {"Collider",
     "Коллайдер"},
    {"Collider (C): drag the collision shape",
     "Коллайдер (C): тянуть форму столкновения"},
    {"Colour",
     "Цвет"},
    {"Column",
     "Столбец"},
    {"Columns",
     "Столбцов"},
    {"Compound parts: %d",
     "Частей составного тела: %d"},
    {"Cone",
     "Конус"},
    {"Cone Half Angle",
     "Полуугол конуса"},
    {"Console",
     "Консоль"},
    {"Continue",
     "Продолжить"},
    {"Continuous",
     "Непрерывно"},
    {"Contrast",
     "Контраст"},
    {"Conversion failed: ",
     "Конвертация не удалась: "},
    {"Convert the whole folder to engine formats",
     "Конвертировать всю папку в форматы движка"},
    {"Convert to .sagemesh",
     "Конвертировать в .sagemesh"},
    {"Convert to .sagetex",
     "Конвертировать в .sagetex"},
    {"Converted %zu, skipped %zu; %.1f -> %.1f KB",
     "Сконвертировано %zu, пропущено %zu; %.1f -> %.1f КБ"},
    {"Copy",
     "Копировать"},
    {"Copy an outside file into the current project folder.\nA model moves together with its .mtl/.bin files and textures.",
     "Скопировать файл со стороны в текущую папку проекта.\nМодель переезжает вместе со своими .mtl/.bin и текстурами."},
    {"Copy the visible lines to the clipboard",
     "Скопировать видимые строки в буфер обмена"},
    {"Could not copy the project file: ",
     "Не удалось скопировать файл проекта: "},
    {"Could not copy: ",
     "Не удалось скопировать: "},
    {"Could not create the folder: ",
     "Не удалось создать папку: "},
    {"Could not save sage.cfg",
     "Не удалось сохранить sage.cfg"},
    {"Could not write the game package",
     "Не удалось записать пакет игры"},
    {"Could not write the theme file",
     "Файл темы записать не удалось"},
    {"Coverage",
     "Облачность"},
    {"Create",
     "Создать"},
    {"Create Animated Model",
     "Создать анимированную модель"},
    {"Create Asset",
     "Создать ассет"},
    {"Create Camera",
     "Создать камеру"},
    {"Create Child",
     "Создать потомка"},
    {"Create Cube",
     "Создать куб"},
    {"Create Decal",
     "Создать наклейку"},
    {"Create Empty",
     "Создать пустой объект"},
    {"Create Light",
     "Создать свет"},
    {"Create Particle Emitter",
     "Создать эмиттер частиц"},
    {"Create Physics Cube",
     "Создать физический куб"},
    {"Create Primitive",
     "Создать примитив"},
    {"Create UI",
     "Создать элемент интерфейса"},
    {"Create a project on the right — it will appear here and open in one click.",
     "Создайте проект справа — он появится здесь и будет открываться одним щелчком."},
    {"Create a sun",
     "Создать солнце"},
    {"Create material",
     "Создать материал"},
    {"Creates <Location>/<Name>/project.sageproj + scenes/ + assets/",
     "Создаст <Папка>/<Имя>/project.sageproj + scenes/ + assets/"},
    {"Creates a .sagemat next to the project assets and moves the current colour of this object into it.",
     "Создаёт .sagemat в ассетах проекта и переносит в него текущий цвет этого объекта."},
    {"Ctrl+D duplicates a line, Alt+Up/Down moves it.",
     "Ctrl+D — дублировать строку, Alt+Up/Down — переставить строку."},
    {"Ctrl+S saves, Ctrl+F finds, Ctrl+/ comments,",
     "Ctrl+S — сохранить, Ctrl+F — найти, Ctrl+/ — комментарий,"},
    {"Cube",
     "Куб"},
    {"Cursor",
     "Курсор"},
    {"Custom Shader",
     "Свой шейдер"},
    {"Cylinder",
     "Цилиндр"},
    {"Darker when pressed",
     "Темнее при нажатии"},
    {"Debug",
     "Отладка"},
    {"Debug: sun visibility",
     "Отладка: видимость солнца"},
    {"Decal",
     "Наклейка"},
    {"Delete",
     "Удалить"},
    {"Delete \"%s\"?",
     "Удалить «%s»?"},
    {"Delete Asset",
     "Удалить ассет"},
    {"Delete Entity",
     "Удалить объект"},
    {"Delete the selected elements",
     "Удалить выделенные элементы"},
    {"Delete the selected objects (",
     "Удалить выделенные объекты ("},
    {"Delete «",
     "Удалить «"},
    {"Deleting an object",
     "Удаление объекта"},
    {"Demo Segments",
     "Сегментов демо-модели"},
    {"Demo scene",
     "Готовая сцена"},
    {"Demo screens",
     "Демо-экраны"},
    {"Density",
     "Плотность"},
    {"Dir Max",
     "Направление, максимум"},
    {"Dir Min",
     "Направление, минимум"},
    {"Direction",
     "Направление"},
    {"Directional (sun)",
     "Направленный (солнце)"},
    {"Disabled alpha",
     "Прозрачность выключенного"},
    {"Disc Colour",
     "Цвет диска"},
    {"Disc Size",
     "Размер диска"},
    {"Display",
     "Дисплей"},
    {"Distance",
     "Дистанция"},
    {"Distances to the parent",
     "Отступы до родителя"},
    {"Distribute",
     "Распределение"},
    {"Do not ask about this action again",
     "Больше не спрашивать об этом действии"},
    {"Do not clip",
     "Не обрезать"},
    {"Double-click a .lua, .vert, .frag or .glsl file in Assets to open it here.",
     "Двойной клик по .lua, .vert, .frag или .glsl в панели Assets открывает файл здесь."},
    {"Down",
     "По вертикали"},
    {"Drag an asset here",
     "Перетащите ассет сюда"},
    {"Drag an object from Hierarchy. The link holds the object's\nid, so renaming it does not break anything.",
     "Перетащите объект из дерева. Ссылка держится за номер\nобъекта, поэтому переименование её не ломает."},
    {"Draws a mesh with a material",
     "Рисует меш с материалом"},
    {"Drives",
     "Диски"},
    {"Drop onto the surface (End)",
     "Опустить на поверхность (End)"},
    {"Dropped onto the surface: ",
     "Опущено на поверхность: "},
    {"Duplicate",
     "Дублировать"},
    {"Duplicate the selected elements",
     "Продублировать выделенные элементы"},
    {"Dynamic",
     "Динамическое"},
    {"Dynamic falls under gravity; Static/Kinematic don't",
     "Динамическое падает под гравитацией; статическое и кинематическое — нет"},
    {"Each icon at the sizes it is actually used at.",
     "Каждая иконка на тех размерах, на которых она и работает."},
    {"Each part of the model has its own material. Empty means the object material above.",
     "У каждой части модели свой материал. Пусто — красится материалом объекта выше."},
    {"Each view is a full scene pass",
     "Каждый вид — полный проход сцены"},
    {"Edit",
     "Правка"},
    {"Edit layout in the viewport",
     "Править вёрстку во вьюпорте"},
    {"Editable text field",
     "Поле для набора текста"},
    {"Edited from the keyboard; the value lives in the Text part",
     "Правится с клавиатуры; значение хранит часть «Текст»"},
    {"Edited in the object inspector; direction is its rotation",
     "Правится в инспекторе объекта; направление — его поворот"},
    {"Editing",
     "Правка"},
    {"Edits apply live to every entity using this material.",
     "Правки применяются сразу ко всем объектам с этим материалом."},
    {"Element",
     "Элемент"},
    {"Elements",
     "Элементы"},
    {"Elevation",
     "Высота над горизонтом"},
    {"Emissive",
     "Свечение"},
    {"Emissive Strength",
     "Сила свечения"},
    {"Emissive multiplier. Values above 1 produce a bloom halo.",
     "Множитель свечения. Значения больше 1 дают ореол (bloom)."},
    {"Empty",
     "Пусто"},
    {"Empty path = procedural demo (\"tentacle\")",
     "Пустой путь — процедурное демо («щупальце»)"},
    {"Empty project",
     "Пустой проект"},
    {"Enable Fog",
     "Включить туман"},
    {"Enable Skybox",
     "Включить небо"},
    {"Enabled",
     "Включено"},
    {"End",
     "К концу"},
    {"End Color",
     "Конечный цвет"},
    {"Enter a file name",
     "Укажите имя файла"},
    {"Enter a project name",
     "Введите имя проекта"},
    {"Enter text",
     "Введите текст"},
    {"Entities: %zu",
     "Объектов: %zu"},
    {"Entity",
     "Объект"},
    {"Environment",
     "Среда"},
    {"Environment: sky, air, ambient light (saved with the scene)",
     "Среда: небо, воздух, окружающий свет (хранится в сцене)"},
    {"Equal gaps between neighbours; the outer ones stay put",
     "Равные зазоры между соседями; крайние остаются на месте"},
    {"Equal step between centers — for rows of unequal widths",
     "Равный шаг между центрами — для рядов из разных по ширине элементов"},
    {"Error (%d)",
     "Ошибки (%d)"},
    {"Even",
     "Поровну"},
    {"Event",
     "Событие"},
    {"Events",
     "События"},
    {"Everyone subscribed to this name hears it: scripts and\nengine code alike.",
     "Его услышат все, кто подписан на это имя: и скрипты,\nи код движка."},
    {"Everything in the editor works inside a project: asset paths, building the game, templates.",
     "Всё в редакторе работает внутри проекта: пути к ассетам, сборка игры, шаблоны."},
    {"Exit",
     "Выход"},
    {"Expand the tools",
     "Развернуть инструменты"},
    {"Export theme to themes/...",
     "Выгрузить тему в themes/..."},
    {"Exposure",
     "Экспозиция"},
    {"FOV",
     "Угол обзора"},
    {"Failed to load: %s",
     "Не загрузилась: %s"},
    {"Failed to open the project: ",
     "Проект не открылся: "},
    {"Far",
     "Дальняя плоскость"},
    {"Far Clip",
     "Дальняя плоскость"},
    {"File",
     "Файл"},
    {"File cannot be read",
     "Файл не читается"},
    {"File name",
     "Имя файла"},
    {"File not found",
     "Файл не найден"},
    {"File not found: ",
     "Файл не найден: "},
    {"File outside the project",
     "Файл вне проекта"},
    {"File reference",
     "Ссылка на файл"},
    {"Files brought into the project: ",
     "Внесено в проект файлов: "},
    {"Fill",
     "Заливка"},
    {"Fill / Tint",
     "Заливка / тон"},
    {"Fill Color",
     "Цвет заливки"},
    {"Fill colour",
     "Цвет заполнения"},
    {"Fill shadow",
     "Тень заливки"},
    {"Fill the parent",
     "На весь родитель"},
    {"Fill with a margin",
     "На весь родитель с полем"},
    {"Find",
     "Найти"},
    {"Find (Enter for next)",
     "Найти (Enter — следующее)"},
    {"Fire, smoke, sparks",
     "Огонь, дым, искры"},
    {"Fit",
     "Вписать"},
    {"Fit content",
     "По содержимому"},
    {"Fixed",
     "Жёсткий"},
    {"Fog",
     "Туман"},
    {"Fog Color",
     "Цвет тумана"},
    {"Fog End",
     "Конец тумана"},
    {"Fog Start",
     "Начало тумана"},
    {"Folder",
     "Папка"},
    {"Folders",
     "Папки"},
    {"Follow",
     "Следовать"},
    {"Follows the parent size instead of a fixed one",
     "Тянется за размером родителя вместо фиксированного"},
    {"Font size",
     "Размер шрифта"},
    {"Foot Lock",
     "Фиксация стоп"},
    {"Forward Scattering",
     "Рассеяние вперёд"},
    {"Found file: %s",
     "Найден файл: %s"},
    {"Four views",
     "Четыре вида"},
    {"Fragment",
     "Фрагментный"},
    {"Frame Cap (0=off)",
     "Предел кадров (0 — без предела)"},
    {"Frame the selection (F)",
     "Показать в кадре (F)"},
    {"Frame, drop, align",
     "Кадрировать, посадить, выровнять"},
    {"Frame: CPU %.2f ms",
     "Кадр: CPU %.2f мс"},
    {"Free",
     "Свободное"},
    {"Friction",
     "Трение"},
    {"Front",
     "Спереди"},
    {"Fullscreen",
     "Полноэкранный"},
    {"GI Static",
     "Статика для GI"},
    {"GI: bake finished — save the scene to write the lightmaps",
     "GI: бейк завершён — сохрани сцену, чтобы записать лайтмапы"},
    {"GI: entities marked static: ",
     "GI: помечено статичными сущностей: "},
    {"GI: no static entities — add the GI Static component",
     "GI: нет статичных сущностей — добавь компонент GI Static"},
    {"GI: the scene changed during the bake — the result was dropped",
     "GI: сцена изменилась во время бейка — результат отброшен"},
    {"GPU, ms",
     "GPU, мс"},
    {"Game",
     "Игра"},
    {"Game (view from the game camera)",
     "Игра (вид из игровой камеры)"},
    {"Game Settings",
     "Настройки игры"},
    {"Game Settings...",
     "Настройки игры..."},
    {"Game Settings: quality and cost of the frame (saved with the project)",
     "Настройки игры: качество и цена кадра (хранятся в проекте)"},
    {"Game configuration (saved into the project as sage.cfg).",
     "Гибкая конфигурация игры (сохраняется в проект как sage.cfg)."},
    {"Game panel renders from the first Primary camera",
     "Панель Game рисует от первой камеры с флагом Primary"},
    {"Game resolution from Game Settings.\nThe layout is computed in it, so this is exactly\nwhat the player will see.",
     "Разрешение игры из настроек игры.\nВ нём считается вся раскладка, то есть это ровно то,\nчто увидит игрок."},
    {"Gamma",
     "Гамма"},
    {"Gaps",
     "Зазоры"},
    {"Gizmo axes: object",
     "Оси гизмо: объекта"},
    {"Gizmo axes: object or world",
     "Оси гизмо: объекта или мира"},
    {"Gizmo axes: world",
     "Оси гизмо: мира"},
    {"Gizmo space: world or local",
     "Пространство гизмо: мировое или локальное"},
    {"Gizmo: move, rotate, scale",
     "Гизмо: перенос, поворот, масштаб"},
    {"Global Illumination (baked)",
     "Глобальное освещение (запечённое)"},
    {"Gradient (a=0 off)",
     "Градиент (a=0 — выключен)"},
    {"Gradient down",
     "Градиент вниз"},
    {"Graphics",
     "Графика"},
    {"Gravity",
     "Гравитация"},
    {"Grid",
     "Сетка"},
    {"Grid and bounds of the selection",
     "Сетка и габариты выделения"},
    {"Grid and snapping",
     "Сетка и привязки"},
    {"Grid cell",
     "Клетка сетки"},
    {"Grid, bounds, UI layout",
     "Сетка, габариты, режим вёрстки"},
    {"Ground",
     "Земля"},
    {"Grounded: %s",
     "На земле: %s"},
    {"Group",
     "Группа"},
    {"Grows",
     "Растёт"},
    {"HUD",
     "Худ"},
    {"HUD under the pause menu",
     "Худ под меню паузы"},
    {"Half Extents",
     "Полуразмеры"},
    {"Half Height",
     "Полувысота"},
    {"Health, progress, loading",
     "Здоровье, прогресс, загрузка"},
    {"Height",
     "Высота"},
    {"Height Falloff",
     "Спад с высотой"},
    {"Help",
     "Справка"},
    {"Hidden",
     "Скрытые"},
    {"Hide",
     "Спрятать"},
    {"Hierarchy",
     "Иерархия"},
    {"High",
     "Высокие"},
    {"Higher draws on top of its siblings",
     "Больше — рисуется поверх соседей"},
    {"Hinge",
     "Шарнир"},
    {"Horizontal",
     "По горизонтали"},
    {"Hotkeys keep working for hidden tools",
     "Горячие клавиши скрытых инструментов работают"},
    {"Hover brightness",
     "Яркость под курсором"},
    {"Hover sprite",
     "Спрайт под курсором"},
    {"Hover, press, click, and an action name for the game",
     "Наведение, нажатие, щелчок и имя действия для игры"},
    {"How hard the character pushes dynamic bodies",
     "С какой силой персонаж толкает динамические тела"},
    {"How tall a step the character climbs without jumping",
     "На какую ступеньку персонаж взбирается без прыжка"},
    {"IK",
     "Обратная кинематика"},
    {"IK Enabled",
     "Включить ОК"},
    {"Icon",
     "Значок"},
    {"Icon Color",
     "Цвет значка"},
    {"Icon name",
     "Имя значка"},
    {"Icon sheet",
     "Страница иконок"},
    {"Id: %d",
     "Номер: %d"},
    {"Image",
     "Картинка"},
    {"Images",
     "Изображения"},
    {"Import Scale",
     "Масштаб при импорте"},
    {"Import failed: ",
     "Импорт не удался: "},
    {"Import settings are baked into the mesh on load.",
     "Настройки импорта запекаются в меш при загрузке."},
    {"Import...",
     "Импорт…"},
    {"Import: ",
     "Импорт: "},
    {"Info",
     "Сведения"},
    {"Inner Cone",
     "Внутренний конус"},
    {"Input",
     "Поле ввода"},
    {"Inspector",
     "Инспектор"},
    {"Instance overrides",
     "Поправки экземпляра"},
    {"Intensity",
     "Яркость"},
    {"Intensity %.2f, direction (%.2f, %.2f, %.2f)",
     "Яркость %.2f, направление (%.2f, %.2f, %.2f)"},
    {"Interactable",
     "Реакция на мышь"},
    {"Interaction",
     "Взаимодействие"},
    {"Interactive",
     "Интерактивный"},
    {"Interface",
     "Интерфейс"},
    {"Interface editor: the game frame at its own resolution",
     "Редактор интерфейса: игровой кадр в его собственном разрешении"},
    {"Interface language changed",
     "Язык интерфейса изменён"},
    {"Interface scale",
     "Масштаб интерфейса"},
    {"It becomes a child of the selected element.",
     "Он становится дочерним к выделенному элементу."},
    {"It did not overwrite your scene — this is a separate copy.",
     "Он не перезаписывал вашу сцену — это отдельная копия."},
    {"Joint",
     "Сочленение"},
    {"Justify",
     "Прижимать"},
    {"Keep the file",
     "Оставить файл"},
    {"Kind",
     "Вид"},
    {"Kind of the argument",
     "Вид аргумента"},
    {"Kind of the value",
     "Вид значения"},
    {"Kinematic",
     "Кинематическое"},
    {"LMB orbits, wheel zooms",
     "ЛКМ — вращать, колесо — приблизить"},
    {"Label",
     "Подпись"},
    {"Landed on nothing: there is no geometry under the box, or it faces away from the decal.",
     "Ни на что не легла: под коробкой нет геометрии, либо она отвёрнута от наклейки."},
    {"Language",
     "Язык"},
    {"Layer",
     "Слой"},
    {"Layout",
     "Положение"},
    {"Layout mode is off — the viewport shows no UI frames.",
     "Режим вёрстки выключен — рамок интерфейса во вьюпорте нет."},
    {"Lays the children out by itself",
     "Сам расставляет детей"},
    {"Left",
     "Влево"},
    {"Left edges",
     "По левому краю"},
    {"Left to right",
     "Слева направо"},
    {"Legacy",
     "Устаревшее"},
    {"Light",
     "Свет"},
    {"Light Shafts",
     "Лучи света"},
    {"Lighting",
     "Освещение"},
    {"Lightmapped",
     "С лайтмапой"},
    {"Line",
     "Строка"},
    {"Line %d, column %d  |  lines: %zu  |  %s  |  %s",
     "Строка %d, столбец %d  |  строк: %zu  |  %s  |  %s"},
    {"Linear distance fog (applied in Shaded mode)",
     "Линейный туман по дальности (виден в режиме Shaded)"},
    {"Lit by object: %s",
     "Светит объект: %s"},
    {"Load",
     "Загрузить"},
    {"Local",
     "Локальное"},
    {"Location",
     "Папка"},
    {"Logic",
     "Логика"},
    {"Loop",
     "Зациклить"},
    {"Low",
     "Низкие"},
    {"Low — weak/old PCs: no shadows or post-processing, 75%% render scale\nMedium — 1024 shadows + tone mapping, no Bloom/SSAO\nHigh — everything on, 2048 shadows (default)\nUltra — 4096 shadows + MSAA 4x\nIn game: environment variable SAGE_QUALITY=low|medium|high|ultra",
     "Low — слабые/старые ПК: без теней и пост-процесса, рендер 75%%\nMedium — тени 1024 + тон-маппинг, без Bloom/SSAO\nHigh — всё включено, тени 2048 (по умолчанию)\nUltra — тени 4096 + MSAA 4x\nВ игре: переменная окружения SAGE_QUALITY=low|medium|high|ultra"},
    {"Lua: OnStart and OnUpdate on this object",
     "Lua: OnStart и OnUpdate на этом объекте"},
    {"MSAA",
     "Сглаживание MSAA"},
    {"Main menu",
     "Главное меню"},
    {"Map value multiplies the factor above; Enter applies the path.",
     "Значение карты множится на коэффициент выше; Enter применяет путь."},
    {"Margin l,t,r,b",
     "Поля л,в,п,н"},
    {"Mark static geometry",
     "Пометить статичную геометрию"},
    {"Marks the object as static for the light bake",
     "Помечает объект статикой для запекания света"},
    {"Mask",
     "Маска"},
    {"Mass",
     "Масса"},
    {"Match width/height",
     "Ширина/высота"},
    {"Material",
     "Материал"},
    {"Material assigned: ",
     "Материал назначен: "},
    {"Material cannot be read",
     "Материал не читается"},
    {"Material created: ",
     "Материал создан: "},
    {"Materials (*.sagemat)",
     "Материалы (*.sagemat)"},
    {"Materials (.sagemat) and models (.obj/.gltf/.glb)",
     "Материалы (.sagemat) и модели (.obj/.gltf/.glb)"},
    {"Max",
     "Максимум"},
    {"Max Angle",
     "Максимальный угол"},
    {"Max Distance",
     "Максимальная дистанция"},
    {"Max Length",
     "Максимальная длина"},
    {"Max Slope",
     "Максимальный уклон"},
    {"Max Value",
     "Максимальное значение"},
    {"Max length",
     "Предел длины"},
    {"Maximum",
     "Максимум"},
    {"Medium",
     "Средние"},
    {"Menu and HUD",
     "Меню и худ"},
    {"Mesh",
     "Меш"},
    {"Mesh Renderer",
     "Отрисовка меша"},
    {"Mesh not loaded",
     "Меш не загружен"},
    {"Mesh replaced: ",
     "Меш заменён: "},
    {"Metallic",
     "Металличность"},
    {"Method",
     "Метод"},
    {"Min",
     "Минимум"},
    {"Min Distance",
     "Минимальная дистанция"},
    {"Min Value",
     "Минимальное значение"},
    {"Minimum",
     "Минимум"},
    {"Mode",
     "Режим"},
    {"Model",
     "Модель"},
    {"Model (.glb)",
     "Модель (.glb)"},
    {"Model material: ",
     "Материал модели: "},
    {"Model materials imported: ",
     "Материалов модели импортировано: "},
    {"Model parts",
     "Части модели"},
    {"Models",
     "Модели"},
    {"Models and images in this folder (including nested) -> .sagemesh/.sagetex.\nAlready converted files are skipped, sources stay in place.",
     "Модели и картинки этой папки (включая вложенные) -> .sagemesh/.sagetex.\nУже сконвертированные пропускаются, исходники остаются."},
    {"Moon",
     "Луна"},
    {"Moon colour",
     "Цвет луны"},
    {"Moon size",
     "Размер луны"},
    {"Move (W)",
     "Перенос (W)"},
    {"Moved into ",
     "Перенесено в "},
    {"Moving failed: ",
     "Перенос не удался: "},
    {"Multiplies the material albedo. White means as in the material.",
     "Множится на albedo материала. Белый — как в материале."},
    {"Multiplies the material opacity.",
     "Множится на непрозрачность материала."},
    {"NEW PROJECT",
     "НОВЫЙ ПРОЕКТ"},
    {"Name",
     "Имя"},
    {"Name the game asks for instead of an entity number",
     "Имя, которое спрашивает игра, вместо номера сущности"},
    {"Near",
     "Ближняя плоскость"},
    {"Needs a %s",
     "Нужен: %s"},
    {"Needs a Rigid Body; only the Jolt backend simulates joints",
     "Нужно твёрдое тело; суставы считает только бэкенд Jolt"},
    {"Needs three elements or more.",
     "Нужно три элемента или больше."},
    {"Net Replicated",
     "Сетевая репликация"},
    {"New Folder",
     "Новая папка"},
    {"New Material (.sagemat)",
     "Новый материал (.sagemat)"},
    {"New Project",
     "Новый проект"},
    {"New Project...",
     "Новый проект…"},
    {"New Scene",
     "Новая сцена"},
    {"New Script (.lua)",
     "Новый скрипт (.lua)"},
    {"New Text File (.txt)",
     "Новый текстовый файл (.txt)"},
    {"New element",
     "Новый элемент"},
    {"New name",
     "Новое имя"},
    {"No Animated Model - goals do nothing",
     "Нет анимированной модели — цели ни на что не влияют"},
    {"No animation clips (bind pose)",
     "Клипов анимации нет (поза привязки)"},
    {"No cover: the prefab has no visible geometry",
     "Обложки нет: в префабе не нашлось видимой геометрии"},
    {"No directional light in the scene — no sun. Direction, colour and intensity live on the object itself.",
     "В сцене нет направленного света — солнца нет. Направление, цвет и яркость задаются на самом объекте."},
    {"No file",
     "Файл не выбран"},
    {"No messages of the selected level",
     "Нет сообщений выбранного уровня"},
    {"No model assigned",
     "Модель не назначена"},
    {"No open files.",
     "Нет открытых файлов."},
    {"No public variables. A script declares them with a Vars\ntable; here you can add your own.",
     "Публичных переменных нет. Скрипт объявляет их таблицей\nVars; здесь можно добавить свои."},
    {"No script attached",
     "Скрипт не прикреплён"},
    {"No such file: ",
     "Файла нет: "},
    {"None",
     "Нет"},
    {"Normal map, tangent space (OpenGL: green is up).",
     "Карта нормалей, tangent-space (OpenGL: зелёный вверх)."},
    {"Normal: tangent-space (OpenGL). Metallic/Rough/AO use R channel.",
     "Нормали — в касательном пространстве (OpenGL). Металличность, шероховатость и AO берутся из канала R."},
    {"Normalize size (max side = 1)",
     "Нормировать размер (наибольшая сторона = 1)"},
    {"Normals",
     "Нормали"},
    {"Not assigned",
     "Не назначен"},
    {"Not baked (%d static entities)",
     "Не запечено (статичных объектов: %d)"},
    {"Not the scene's sun: a directional light with a lower number in the hierarchy is already the sun, and only one takes part in the frame.",
     "Это не солнце сцены: солнцем уже работает направленный свет с меньшим номером в иерархии, а в кадре участвует только одно."},
    {"Nothing happens yet. A link lets this element send an event\nor call a method on another object by itself.",
     "Пока ничего не происходит. Связь позволяет элементу самому\nпослать событие или позвать метод у другого объекта."},
    {"Nothing here yet.",
     "Пока пусто."},
    {"Nothing matches the search.",
     "Ничего не найдено по запросу."},
    {"Nothing selected",
     "Ничего не выбрано"},
    {"Nothing to convert: no models or images in the folder",
     "Конвертировать нечего: в папке нет моделей и картинок"},
    {"Nothing — drag an object here",
     "Ничего — перетащите объект сюда"},
    {"Nowhere to drop the material — no object under the cursor",
     "Материал ронять некуда — под курсором нет объекта"},
    {"Number",
     "Число"},
    {"OPEN ANOTHER",
     "ОТКРЫТЬ ДРУГОЙ"},
    {"Object",
     "Объект"},
    {"Object is gone (id ",
     "Объекта больше нет (номер "},
    {"Object reference",
     "Ссылка на объект"},
    {"Off",
     "Выключено"},
    {"Offset",
     "Смещение"},
    {"One element — aligned to its parent",
     "Один элемент — равняется по родителю"},
    {"Only a model or a prefab can be added to the scene",
     "В сцену можно добавить модель или префаб"},
    {"Only interface entities are listed here.\nThe rest of the scene is in the Hierarchy.",
     "Здесь перечислены только элементы интерфейса.\nОстальная сцена — в иерархии."},
    {"Only the folders and an empty scene",
     "Только структура папок и пустая сцена"},
    {"Opacity",
     "Непрозрачность"},
    {"Open",
     "Открыть"},
    {"Open Project",
     "Открыть проект"},
    {"Open Project...",
     "Открыть проект…"},
    {"Open Scene",
     "Открыть сцену"},
    {"Open Scene...",
     "Открыть сцену…"},
    {"Open console",
     "Открыть консоль"},
    {"Open in editor",
     "Открыть в редакторе"},
    {"Open project",
     "Открыть проект"},
    {"Open scene",
     "Открыть сцену"},
    {"Open the copy",
     "Открыть копию"},
    {"Open the project folder",
     "Открыть папку проекта"},
    {"Outer Cone",
     "Внешний конус"},
    {"Outlines of all elements",
     "Рамки всех элементов"},
    {"Output dir",
     "Папка вывода"},
    {"Override the material",
     "Переопределить материал"},
    {"PAUSED",
     "ПАУЗА"},
    {"PBR",
     "PBR"},
    {"PLAYING",
     "ИГРА ИДЁТ"},
    {"Packages SagePlayer + project '%s' into a runnable game",
     "Упакует SagePlayer и проект «%s» в готовую к запуску игру"},
    {"Padding (l,t,r,b)",
     "Поля (л,в,п,н)"},
    {"Padding X",
     "Отступ по X"},
    {"Padding l,t,r,b",
     "Отступы л,в,п,н"},
    {"Painted with the object material.",
     "Красится материалом объекта."},
    {"Panel",
     "Панель"},
    {"Panel, label, image or bar on screen",
     "Панель, надпись, картинка или полоса на экране"},
    {"Panels",
     "Панели"},
    {"Params: %d (edit in the .sagemat file)",
     "Параметров: %d (правятся в файле .sagemat)"},
    {"Part ",
     "Часть "},
    {"Particle Emitter",
     "Эмиттер частиц"},
    {"Parts",
     "Части"},
    {"Parts override the single shape above",
     "Части заменяют одиночную форму выше"},
    {"Password",
     "Пароль"},
    {"Path",
     "Путь"},
    {"Path to a .sage file (or double-click in the Assets panel)",
     "Путь к файлу .sage (или двойной клик в панели Assets)"},
    {"Path to project.sageproj or to a project folder",
     "Путь к project.sageproj или к папке проекта"},
    {"Pause",
     "Приостановить"},
    {"Per-frame numbers swing by tens of percent because of the OS scheduler.\nThe 30-frame average is what you actually read.\n\nGPU time lags three frames behind: asking for it right away means waiting\nfor the card, that is, creating the delay you are measuring.",
     "Покадровые значения скачут на десятки процентов от планировщика ОС.\nУсреднение по 30 кадрам — то, по чему и смотрят.\n\nВремя GPU отстаёт на три кадра: спросить его сразу значит дождаться\nвидеокарты, то есть своим измерением создать измеряемую задержку."},
    {"Perspective",
     "Перспектива"},
    {"Physics",
     "Физика"},
    {"Pivot",
     "Точка привязки"},
    {"Pixel Art (nearest, no mips)",
     "Пиксель-арт (ближайший сосед, без мипов)"},
    {"Pixel Scale",
     "Масштаб пикселя"},
    {"Pixel art",
     "Пиксель-арт"},
    {"Pixel scale",
     "Масштаб пикселя"},
    {"Pixels",
     "Пиксели"},
    {"Place in scene",
     "Поставить в сцену"},
    {"Placed in the scene: ",
     "Поставлено в сцену: "},
    {"Placeholder",
     "Подсказка в поле"},
    {"Plane",
     "Плоскость"},
    {"Plant Height",
     "Высота постановки"},
    {"Play",
     "Играть"},
    {"Playing",
     "Проигрывается"},
    {"Point",
     "Точечный"},
    {"Point, spot or directional light",
     "Точечный свет, прожектор или солнце"},
    {"Pole",
     "Направляющая"},
    {"Position",
     "Позиция"},
    {"Position, rotation, scale, color and primitive are replicated",
     "Передаются позиция, поворот, масштаб, цвет и вид примитива"},
    {"Post-Process",
     "Пост-эффекты"},
    {"Post-Processing",
     "Пост-обработка"},
    {"Prefab saved: ",
     "Префаб сохранён: "},
    {"Preset",
     "Заготовка"},
    {"Preset:",
     "Пресет:"},
    {"Pressed brightness",
     "Яркость при нажатии"},
    {"Pressed sprite",
     "Спрайт при нажатии"},
    {"Preview",
     "Превью"},
    {"Primary",
     "Главная"},
    {"Primitives, light and a HUD — shows what the engine can do",
     "Примитивы, свет и худ — показывает, что умеет движок"},
    {"Probe cell size",
     "Шаг сетки проб"},
    {"Procedural gradient (top -> horizon), no textures",
     "Процедурный градиент (зенит -> горизонт), без текстур"},
    {"Profiler",
     "Профилировщик"},
    {"Progress or health bar",
     "Полоса прогресса или здоровья"},
    {"Project",
     "Проект"},
    {"Project Launcher...",
     "Окно проектов…"},
    {"Project Scenes",
     "Сцены проекта"},
    {"Project assets",
     "Ассеты проекта"},
    {"Project folder or .sageproj",
     "Папка проекта или .sageproj"},
    {"Project name",
     "Имя проекта"},
    {"Project:",
     "Проект:"},
    {"Projected triangles: %d",
     "Спроецировано треугольников: %d"},
    {"Projection goes along -Z; Scale sets the size",
     "Проекция идёт вдоль -Z; размер задаёт Scale"},
    {"Projection of the active view",
     "Проекция активного вида"},
    {"Projects (*.sageproj)",
     "Проекты (*.sageproj)"},
    {"Projects a texture onto surfaces underneath",
     "Проецирует текстуру на поверхности под собой"},
    {"Properties",
     "Свойства"},
    {"Pushes the selected elements back inside the screen.",
     "Придвигает выделенные элементы обратно внутрь экрана."},
    {"Quality",
     "Качество"},
    {"Quality and cost of the frame — saved into the project as sage.cfg. The look of the scene (sky, fog, ambient) is in Environment; light sources are objects in the hierarchy.",
     "Качество и цена кадра — сохраняются в проект, в sage.cfg. Вид сцены (небо, туман, окружающий свет) — в окне «Среда»; источники света — объекты в иерархии."},
    {"Quick actions",
     "Быстрые действия"},
    {"RECENT",
     "НЕДАВНИЕ"},
    {"Radius",
     "Радиус"},
    {"Range",
     "Дальность"},
    {"Rate (p/s)",
     "Частота (частиц/с)"},
    {"Ray Steps",
     "Шагов по лучу"},
    {"Re-bake lighting after changes (Lighting panel)",
     "После правок освещение стоит перезапечь (панель Lighting)"},
    {"Reacts to the mouse: hover, press, click",
     "Реагирует на мышь: наведение, нажатие, щелчок"},
    {"Reacts to the mouse: hover, press, focus",
     "Реагирует на мышь: наведение, нажатие, фокус"},
    {"Read Only",
     "Только чтение"},
    {"Read only",
     "Только чтение"},
    {"Realtime (re-capture every frame)",
     "В реальном времени (пересъёмка каждый кадр)"},
    {"Realtime = 6 scene passes per frame - use sparingly",
     "Реальное время — шесть проходов сцены на кадр, включайте с оглядкой"},
    {"Rebuild",
     "Пересобрать"},
    {"Recenter (AABB -> origin)",
     "Отцентровать (габарит -> начало координат)"},
    {"Rect (Y): drag the faces of the bounding box",
     "Рамка (Y): тянуть за грани габаритной коробки"},
    {"Rectangle",
     "Прямоугольник"},
    {"Redo",
     "Повторить"},
    {"Reference",
     "Опорное разрешение"},
    {"Reference resolution",
     "Опорное разрешение"},
    {"Reflection Probe",
     "Зонд отражений"},
    {"Refresh",
     "Обновить"},
    {"Reimport",
     "Переимпортировать"},
    {"Release Time",
     "Время затухания"},
    {"Reload",
     "Перечитать"},
    {"Remove",
     "Убрать"},
    {"Remove Animated Model",
     "Убрать анимированную модель"},
    {"Remove Camera",
     "Убрать камеру"},
    {"Remove Character Controller",
     "Убрать контроллер персонажа"},
    {"Remove Collider",
     "Убрать коллайдер"},
    {"Remove Emitter",
     "Убрать эмиттер"},
    {"Remove Goal",
     "Убрать цель"},
    {"Remove IK",
     "Убрать обратную кинематику"},
    {"Remove Joint",
     "Убрать сустав"},
    {"Remove Light",
     "Убрать свет"},
    {"Remove Part",
     "Убрать часть"},
    {"Remove Reflection Probe",
     "Убрать зонд отражений"},
    {"Remove Rigid Body",
     "Убрать твёрдое тело"},
    {"Remove Script",
     "Убрать скрипт"},
    {"Remove UI Element",
     "Убрать элемент интерфейса"},
    {"Remove from the list (the project is not deleted)",
     "Убрать из списка (проект не удаляется)"},
    {"Remove the link",
     "Убрать связь"},
    {"Remove the variable",
     "Убрать переменную"},
    {"Rename",
     "Переименовать"},
    {"Rename Asset",
     "Переименовать ассет"},
    {"Render",
     "Рендер"},
    {"Render Scale",
     "Масштаб рендера"},
    {"Render Scale < 1 is faster; > 1 supersamples (sharper).",
     "Render Scale < 1 — быстрее; > 1 — суперсэмплинг (чётче)."},
    {"Render mode",
     "Режим отрисовки"},
    {"Replace this object's mesh",
     "Заменить меш этого объекта"},
    {"Replaces the element parts with the preset ones",
     "Заменяет части элемента на части заготовки"},
    {"Rescan project",
     "Пересканировать проект"},
    {"Reset Layout",
     "Сбросить раскладку"},
    {"Reset scale",
     "Обычный масштаб"},
    {"Reset to Defaults",
     "Вернуть значения по умолчанию"},
    {"Reset view",
     "Сбросить вид"},
    {"Resizable",
     "Изменяемый размер"},
    {"Resolution",
     "Разрешение"},
    {"Restitution",
     "Упругость"},
    {"Restore panels",
     "Вернуть панели"},
    {"Restore scene?",
     "Восстановить сцену?"},
    {"Resume",
     "Продолжить"},
    {"Revert",
     "Откатить"},
    {"Right",
     "Вправо"},
    {"Right edges",
     "По правому краю"},
    {"Right to left",
     "Справа налево"},
    {"Right-click to create a folder, script, material or text file.",
     "Правый клик создаёт папку, скрипт, материал или текстовый файл."},
    {"Rigid Body",
     "Твёрдое тело"},
    {"Root /",
     "Корень /"},
    {"Root Motion",
     "Движение корня"},
    {"Root order",
     "Порядок корней"},
    {"Rotate (E)",
     "Поворот (E)"},
    {"Rotation",
     "Поворот"},
    {"Roughness",
     "Шероховатость"},
    {"Round to the grid",
     "Округлить по сетке"},
    {"Rounded",
     "Скруглённый"},
    {"Rounded background, border, gradient, shadow",
     "Скруглённая подложка, рамка, градиент, тень"},
    {"Rounding",
     "Скругление"},
    {"Row",
     "Строка"},
    {"Run",
     "Запуск"},
    {"Run the scene (it is restored on Stop)",
     "Запустить сцену (сцена будет восстановлена по Stop)"},
    {"Runs in Play mode: OnStart(entity), OnUpdate(entity, dt)",
     "Выполняется в режиме игры: OnStart(entity), OnUpdate(entity, dt)"},
    {"SAGE Engine",
     "SAGE Engine"},
    {"SAGE Engine %s",
     "SAGE Engine %s"},
    {"SAGE projects (*.sageproj)",
     "Проекты SAGE (*.sageproj)"},
    {"START FROM",
     "НАЧАТЬ С"},
    {"SagePlayer not found. Put it next to the editor, build the SagePlayer target, or set SAGE_PLAYER_PATH. Looked in:",
     "SagePlayer не найден. Положите его рядом с редактором, соберите цель SagePlayer или задайте SAGE_PLAYER_PATH. Искали:"},
    {"Samples / texel",
     "Выборок на тексель"},
    {"Saturation",
     "Насыщенность"},
    {"Save",
     "Сохранить"},
    {"Save Material",
     "Сохранить материал"},
    {"Save Scene",
     "Сохранить сцену"},
    {"Save Scene As",
     "Сохранить сцену как"},
    {"Save Scene As...",
     "Сохранить сцену как…"},
    {"Save as Prefab",
     "Сохранить как префаб"},
    {"Save to Project",
     "Сохранить в проект"},
    {"Scale",
     "Масштаб"},
    {"Scale (R)",
     "Масштаб (R)"},
    {"Scale mode",
     "Способ масштабирования"},
    {"Scale to reference",
     "Масштаб под опорное"},
    {"Scale with screen size",
     "Подгонять под размер экрана"},
    {"Scaling rules for this UI root",
     "Правила масштабирования для этого корня интерфейса"},
    {"Scene",
     "Сцена"},
    {"Scene changed since bake — re-bake",
     "Сцена менялась после запекания — стоит перезапечь"},
    {"Scene lights",
     "Источники света сцены"},
    {"Scene: %s  |  Entities: %zu",
     "Сцена: %s  |  объектов: %zu"},
    {"Scenes (*.sage)",
     "Сцены (*.sage)"},
    {"Screen:",
     "Экран:"},
    {"Script",
     "Скрипт"},
    {"Script assigned: ",
     "Скрипт назначен: "},
    {"Scripts (*.lua)",
     "Скрипты (*.lua)"},
    {"Search...",
     "Поиск…"},
    {"Section",
     "Участок"},
    {"Select",
     "Выбрать"},
    {"Select an element on the canvas or in the list on the left.",
     "Выберите элемент на холсте или в списке слева."},
    {"Select an interface element.",
     "Выделите элемент интерфейса."},
    {"Select an object in the viewport or Hierarchy, or a file in Assets.",
     "Выберите объект во вьюпорте или в Hierarchy, либо файл в Assets."},
    {"Send backward",
     "Ниже соседей"},
    {"Settings",
     "Настройки"},
    {"Settings saved: sage.cfg",
     "Настройки сохранены: sage.cfg"},
    {"Settings...",
     "Настройки…"},
    {"Shaded",
     "С освещением"},
    {"Shader limit: %d point + %d spot lights per frame",
     "Предел шейдера: %d точечных и %d прожекторов на кадр"},
    {"Shadow",
     "Тень"},
    {"Shadow Resolution",
     "Разрешение теней"},
    {"Shadow colour",
     "Цвет тени"},
    {"Shadows",
     "Тени"},
    {"Shape",
     "Форма"},
    {"Sheet: %d x %d px",
     "Лист: %d x %d пикс."},
    {"Shininess",
     "Блеск"},
    {"Show",
     "Показать"},
    {"Show Grid",
     "Показать сетку"},
    {"Show all",
     "Показать всё"},
    {"Show everything",
     "Показать всё"},
    {"Show outside",
     "Не обрезать"},
    {"Show the grid",
     "Показывать сетку"},
    {"Show the sun",
     "Показать солнце"},
    {"Side",
     "Сбоку"},
    {"Side padding",
     "Боковой отступ"},
    {"Single view",
     "Один вид"},
    {"Size",
     "Размер"},
    {"Size from content",
     "Размер по содержимому"},
    {"Size: %llu bytes",
     "Размер: %llu байт"},
    {"Sizes are scaled by the entity's Transform scale",
     "Размеры домножаются на масштаб из Transform объекта"},
    {"Skeletal animation clips",
     "Клипы скелетной анимации"},
    {"Sky",
     "Небо"},
    {"Sky Horizon",
     "Небо у горизонта"},
    {"Sky Top",
     "Небо в зените"},
    {"Sky tints upward faces, Ground — downward",
     "Sky красит грани, смотрящие вверх, Ground — вниз"},
    {"Skybox",
     "Небо"},
    {"Slider",
     "Ползунок"},
    {"Slider or checkbox value",
     "Значение ползунка или галки"},
    {"Smoothing",
     "Сглаживание"},
    {"Snap",
     "Привязка"},
    {"Snap radius",
     "Радиус привязки"},
    {"Snap step for the current mode.\nWhen building from blocks, set it to the block size.",
     "Шаг привязки для текущего режима.\nДля постройки из блоков ставьте его равным размеру блока."},
    {"Snap to edges and centers",
     "Привязка к краям и центрам"},
    {"Snap to edges and centers of neighbours",
     "Привязка к краям и центрам соседей"},
    {"Snap to it",
     "Привязка к ней"},
    {"Snap to step",
     "Привязка к шагу"},
    {"Snap to the grid",
     "Привязка к сетке"},
    {"Snapping and its step",
     "Привязка и её шаг"},
    {"Sort order",
     "Порядок между корнями"},
    {"Source",
     "Источник"},
    {"Space between",
     "Поровну между"},
    {"Spacing",
     "Зазор"},
    {"Speed",
     "Скорость"},
    {"Sphere",
     "Сфера"},
    {"Spin",
     "Вращение"},
    {"Spot",
     "Прожектор"},
    {"Sprite (x,y,w,h)",
     "Спрайт (x,y,ш,в)"},
    {"Sprite from a sheet",
     "Спрайт с листа"},
    {"Sprite on hover",
     "Спрайт под курсором"},
    {"Sprite when pressed",
     "Спрайт при нажатии"},
    {"Sprite x,y,w,h",
     "Спрайт: x, y, ширина, высота"},
    {"Stars",
     "Звёзды"},
    {"Start",
     "Старт"},
    {"Start Color",
     "Начальный цвет"},
    {"Start from",
     "Начать с"},
    {"Startup folder",
     "Папка запуска"},
    {"Static",
     "Статическое"},
    {"Static occluder for baked GI; lightmapped = has own lightmap",
     "Статичный перекрыватель для запечённого GI; «с лайтмапой» — есть своя карта освещения"},
    {"Steeper than this and the character slides",
     "Круче — персонаж соскальзывает"},
    {"Step",
     "Шаг"},
    {"Step Height",
     "Высота ступеньки"},
    {"Steps decide banding, accumulation decides grain, scale decides sharpness. Turn accumulation off and the same number of steps becomes visibly noisy.",
     "Шаги решают полосы, накопление — зерно, масштаб — резкость. Выключите накопление, и то же число шагов станет заметно зернистым."},
    {"Stop",
     "Стоп"},
    {"Stop and restore the scene",
     "Остановить и вернуть сцену как была"},
    {"Strength",
     "Сила"},
    {"Stretch",
     "Растяжение"},
    {"Stretch across",
     "Растягивать поперёк"},
    {"Style",
     "Стиль"},
    {"Subsystems: %zu (all v1)",
     "Подсистемы: %zu (все v1)"},
    {"Sun",
     "Солнце"},
    {"Sun and moon in the sky",
     "Солнце и луна на небе"},
    {"Sun colour",
     "Цвет солнца"},
    {"Sun disc along the sun direction, moon opposite it,\nstars appear as the sun goes below the horizon.",
     "Диск солнца по направлению Sun Direction, луна противоходом,\nзвёзды проступают, когда солнце уходит за горизонт."},
    {"Sun of the scene",
     "Солнце сцены"},
    {"Sun size",
     "Размер солнца"},
    {"Sun: shines along the object's forward (-Z of its rotation) from infinity and has no range. Shadows are cascaded maps. The sun is the directional light with the lowest number in the hierarchy; a second one takes no part in the frame.",
     "Солнце: светит вдоль «вперёд» объекта (-Z поворота) из бесконечности, дальности не имеет. Тени — каскадные карты. Солнцем считается направленный свет с наименьшим номером в иерархии; второй такой свет в кадре не участвует."},
    {"Supported:",
     "Поддерживаются:"},
    {"Surface Offset",
     "Отступ от поверхности"},
    {"Target (world)",
     "Цель (в мире)"},
    {"Target Id (-1 = world)",
     "Номер цели (-1 — мир)"},
    {"Temporal Accumulation",
     "Накопление по кадрам"},
    {"Temporal Blend",
     "Доля истории"},
    {"Texel Scale",
     "Масштаб текселя"},
    {"Texels / unit",
     "Текселей на единицу"},
    {"Text",
     "Текст"},
    {"Text Color",
     "Цвет текста"},
    {"Text Input",
     "Поле ввода"},
    {"Text Scale",
     "Масштаб текста"},
    {"Text on the element",
     "Надпись на элементе"},
    {"Texture",
     "Текстура"},
    {"Texture not loaded (press Load)",
     "Текстура не загружена (нажмите «Загрузить»)"},
    {"Texture or a sprite from a sheet",
     "Текстура или спрайт с листа"},
    {"Texture: ",
     "Текстура: "},
    {"That folder already exists and is not empty",
     "Такая папка уже есть и не пуста"},
    {"The built game will not find it. Bring it into the project:",
     "В собранной игре не найдётся. Внесите его в проект:"},
    {"The cone shines along the object's forward (-Z of its rotation). Its shadow is a separate map in the atlas: there are few, and they go to the brightest sources.",
     "Конус светит вдоль «вперёд» объекта (-Z поворота). Тень — отдельная карта в атласе: их немного, и достаются они самым ярким источникам."},
    {"The element stays where it is — only Offset is recomputed.",
     "Элемент остаётся на месте — пересчитывается только Offset."},
    {"The engine's own format: loads without parsing and weighs less.\nThe source file stays where it is.",
     "Свой формат движка: грузится без разбора и весит меньше.\nИсходный файл остаётся на месте."},
    {"The file is gone or damaged — details in the console.",
     "Файл удалён или повреждён — подробности в консоли."},
    {"The file is missing. Put it back or reassign the asset —\nonly the .meta sidecar could have caught a rename made outside the editor.",
     "Файла нет. Верните его на место или переназначьте ассет —\nпереименование мимо редактора мог поймать только сайдкар .meta."},
    {"The filter matched nothing",
     "Ничего не найдено по фильтру"},
    {"The folder already contains ",
     "В папке уже есть "},
    {"The folder is not accessible: ",
     "Папка недоступна: "},
    {"The game looks through this object",
     "Игра смотрит через этот объект"},
    {"The look comes from the material. Turn the switch on only to make THIS object differ from others sharing the same material.",
     "Вид берётся из материала. Включайте переключатель, только чтобы ЭТОТ объект отличался от других с тем же материалом."},
    {"The look of an object is defined by its material.",
     "Вид объекта задаёт материал."},
    {"The look of the scene's world: sky, air, ambient light. Saved with the scene. Light SOURCES are objects — see the hierarchy. Quality and cost are in Game Settings.",
     "Как выглядит мир сцены: небо, воздух, окружающий свет. Хранится в сцене. Сами ИСТОЧНИКИ света — объекты, они в иерархии. Качество и цена кадра — в настройках игры."},
    {"The model failed to load: ",
     "Модель не загрузилась: "},
    {"The model material was not saved — details in Console",
     "Материал модели не сохранён — подробности в Console"},
    {"The most expensive pass of the frame: light in the air and\nvolumetric clouds. Visible in the viewport and in the Game\npanel exactly as in the built game.",
     "Самый дорогой проход кадра: свет в воздухе и объёмные\nоблака. Виден во вьюпорте и в панели Game ровно так же,\nкак в собранной игре."},
    {"The name cannot be empty",
     "Имя не может быть пустым"},
    {"The name reaches the object's script as OnMessage(entity,\nname, data) — the same path SendMessage uses.",
     "Имя придёт в скрипт объекта как OnMessage(entity, name,\ndata) — тем же путём, что и SendMessage."},
    {"The object falls and collides",
     "Объект падает и сталкивается"},
    {"The parent lays its children out: row, column, grid",
     "Родитель раскладывает детей: строка, столбец, сетка"},
    {"The prefab could not be placed: ",
     "Префаб не поставился: "},
    {"The previous session seems to have crashed",
     "Похоже, прошлый запуск завершился аварийно"},
    {"The properties of this entity belong to it alone.",
     "Свойства этой сущности — только её."},
    {"The server replicates this object to clients",
     "Сервер реплицирует этот объект клиентам"},
    {"The server sends this object to clients; they follow it",
     "Сервер рассылает этот объект клиентам, они повторяют его движение"},
    {"The shape physics uses for collisions",
     "Форма, которой физика считает столкновения"},
    {"The sky or its celestials are off — see Environment.",
     "Небо или его светила выключены — см. окно «Среда»."},
    {"The subtree is clipped by this element's rectangle",
     "Поддерево обрезается прямоугольником этого элемента"},
    {"The subtree is masked by this rectangle",
     "Поддерево обрезается этим прямоугольником"},
    {"The subtree is masked by this rectangle (lists, minimaps)",
     "Поддерево обрезается этим прямоугольником (списки, миникарты)"},
    {"The sun's disc, direction and colour are on the sun object — select it in the hierarchy.",
     "Диск солнца, его направление и цвет — на самом объекте-солнце: выберите его в иерархии."},
    {"The world of this project is built by scripts. Press Play to walk through the zones;\nin the stopped editor the scene holds only the world root and the player.",
     "Мир этого проекта собирают скрипты. Нажмите Play, чтобы пройтись по зонам;\nв остановленном редакторе в сцене лежат только корень мира и игрок."},
    {"Theme changed",
     "Оформление изменено"},
    {"Theme saved:",
     "Тема записана:"},
    {"There are no interface elements yet. Add one with the Element button above.",
     "Элементов интерфейса пока нет. Добавьте кнопкой «Элемент» выше."},
    {"There are unsaved changes (Ctrl+S)",
     "Есть несохранённые правки (Ctrl+S)"},
    {"There is no editor for this file type.",
     "Для этого типа файла редактора нет."},
    {"There is no surface under the selection",
     "Под выделенным нет поверхности"},
    {"This cannot be undone.",
     "Это действие необратимо."},
    {"This file cannot be applied to an object",
     "Этот файл нельзя применить к объекту"},
    {"This file cannot be assigned to an object",
     "Этот файл на объект не назначается"},
    {"This folder is empty.",
     "Папка пуста."},
    {"This light IS the sun: it casts the cascaded shadows and it is where the procedural sky draws its disc. Point it by rotating the object, or by azimuth and elevation below.",
     "Этот свет и есть солнце: он отбрасывает каскадные тени, и по нему процедурное небо рисует диск. Направляют его поворотом объекта или азимутом и высотой ниже."},
    {"This scene is not from this project — assets may not be found",
     "Сцена не из этого проекта — ассеты могут не найтись"},
    {"This template is not installed next to the editor",
     "Этот шаблон не установлен рядом с редактором"},
    {"This template is not installed next to the editor:",
     "Этот шаблон не установлен рядом с редактором:"},
    {"Three numbers",
     "Три числа"},
    {"Tidies up a screen that was built before snapping was on.",
     "Приводит в порядок экран, собранный до включения привязок."},
    {"Ties this body to another one",
     "Связывает это тело с другим"},
    {"Timestamps are not ready yet — wait a few frames.",
     "Метки ещё не созрели — подождите несколько кадров."},
    {"Tint",
     "Тон"},
    {"Toggle (checkbox)",
     "Галка (два значения)"},
    {"Top",
     "Сверху"},
    {"Top Center",
     "Сверху по центру"},
    {"Top Left",
     "Слева сверху"},
    {"Top Right",
     "Справа сверху"},
    {"Top center",
     "По центру сверху"},
    {"Top edges",
     "По верхнему краю"},
    {"Top left",
     "Слева сверху"},
    {"Top right",
     "Справа сверху"},
    {"Top to bottom",
     "Сверху вниз"},
    {"Track colour",
     "Цвет дорожки"},
    {"Transform",
     "Преобразование"},
    {"Transparency",
     "Прозрачность"},
    {"Triangles: %d, bounds %.2f x %.2f x %.2f",
     "Треугольников: %d, габарит %.2f x %.2f x %.2f"},
    {"Turn on",
     "Включить"},
    {"Turn on layout mode (U)",
     "Включить режим вёрстки (U)"},
    {"Two columns",
     "Два столбца"},
    {"Two numbers",
     "Два числа"},
    {"Type",
     "Тип"},
    {"UI Element",
     "Элемент интерфейса"},
    {"UI Layout",
     "Вёрстка"},
    {"UI layout mode (U)",
     "Режим вёрстки интерфейса (U)"},
    {"UI layout tools",
     "Инструменты вёрстки интерфейса"},
    {"Ultra",
     "Максимальные"},
    {"Undo",
     "Отменить"},
    {"Units per second; 0 — jump straight to the value",
     "Единиц в секунду; 0 — сразу к значению"},
    {"Unlit",
     "Без освещения"},
    {"Unparent",
     "Отвязать от родителя"},
    {"Up",
     "Вверх"},
    {"Use Limits",
     "Ограничения"},
    {"Use Pole",
     "Использовать направляющую"},
    {"VSync",
     "Вертикальная синхронизация"},
    {"Value",
     "Значение"},
    {"Value (0..1)",
     "Значение (0..1)"},
    {"Variables",
     "Переменные"},
    {"Vector icon of the engine",
     "Векторный значок движка"},
    {"Vertex",
     "Вершинный"},
    {"Vertical",
     "По вертикали"},
    {"View",
     "Обзор"},
    {"View layout and projection",
     "Раскладка видов и проекция"},
    {"Viewport",
     "Вьюпорт"},
    {"Viewport grid",
     "Сетка вьюпорта"},
    {"Viewport layout.\nEach view is a full scene pass,\nso extra views cost frames.",
     "Раскладка вьюпорта.\nКаждый вид — полный проход сцены,\nпоэтому лишние виды стоят кадров."},
    {"Views",
     "Виды"},
    {"Vignette",
     "Виньетка"},
    {"Visible",
     "Видимый"},
    {"Volumetric Intensity",
     "Сила рассеяния"},
    {"Volumetric Light",
     "Объёмный свет"},
    {"Volumetric Light...",
     "Объёмный свет..."},
    {"Volumetric Scale",
     "Разрешение прохода"},
    {"Volumetric light and clouds are a frame cost, not a scene property — they live in the engine settings.",
     "Объёмный свет и облака — цена кадра, а не свойство сцены: они в настройках движка."},
    {"Volumetrics",
     "Объёмный свет"},
    {"Walking, jumping, stairs",
     "Ходьба, прыжки, ступеньки"},
    {"Warn (%d)",
     "Предупр. (%d)"},
    {"Weight",
     "Вес"},
    {"What to show in the toolbar",
     "Что показывать в строке инструментов"},
    {"Wheel zooms, middle button pans, Shift+F fits everything including what ran off.",
     "Колесо — масштаб, средняя кнопка — панорама, Shift+F — вписать всё, включая уехавшее."},
    {"When",
     "Когда"},
    {"Where it glows and where it does not. Multiplied by the emissive colour and strength.",
     "Где светится, а где нет. Умножается на цвет и силу свечения."},
    {"Where the element holds on when the screen changes size.",
     "За что элемент держится при смене размера экрана."},
    {"Where to build the game",
     "Куда собрать игру"},
    {"Where to create the project",
     "Куда создать проект"},
    {"Where to put the project",
     "Куда положить проект"},
    {"Where to save the material",
     "Куда сохранить материал"},
    {"Whether a pass runs at all and at what resolution. Which light casts those shadows is a property of the light object.",
     "Выполняется ли проход вообще и в каком разрешении. А какой источник отбрасывает тени — свойство самого объекта-света."},
    {"Which point of the element lands on the anchor",
     "Какая точка элемента попадает на якорь"},
    {"Whole number",
     "Целое число"},
    {"Width",
     "Ширина"},
    {"Width follows the content",
     "Ширина подгоняется под содержимое"},
    {"Width from text",
     "Ширина по тексту"},
    {"Will create:",
     "Будет создано:"},
    {"Will select: %s",
     "Будет выбрана: %s"},
    {"Window",
     "Окно"},
    {"Window settings apply when the game starts.",
     "Оконные параметры применяются при запуске игры."},
    {"Windowed",
     "В окне"},
    {"Windows menu returns any panel, or restore the default layout.",
     "Любую панель вернёт меню «Окна», а раскладку по умолчанию — «Сбросить раскладку»."},
    {"Wireframe",
     "Каркас"},
    {"World",
     "Мировое"},
    {"Wrap",
     "Перенос строк"},
    {"Yes / no",
     "Да / нет"},
    {"You can bring the question back in Window -> Settings.",
     "Вернуть вопрос можно в Window -> Settings."},
    {"You can drop a model, a prefab or a material into the scene",
     "В сцену можно бросить модель, префаб или материал"},
    {"Zoom",
     "Масштаб"},
    {"[%s] %s  (x%d)",
     "[%s] %s  (x%d)"},
    {"always",
     "всегда"},
    {"and are edited right here.",
     "правятся здесь же."},
    {"bone not found in skeleton",
     "кость в скелете не найдена"},
    {"cross-fading %.0f%%",
     "переход %.0f%%"},
    {"error",
     "ошибка"},
    {"errors",
     "ошибки"},
    {"errors (many)",
     "ошибок"},
    {"file",
     "файл"},
    {"for example: game.start",
     "например: game.start"},
    {"just now",
     "только что"},
    {"material",
     "материал"},
    {"model",
     "модель"},
    {"no",
     "нет"},
    {"not installed",
     "не установлен"},
    {"nothing selected",
     "ничего не выбрано"},
    {"part",
     "часть"},
    {"prefab",
     "префаб"},
    {"scene",
     "сцена"},
    {"scene object",
     "объект сцены"},
    {"script",
     "скрипт"},
    {"sound",
     "звук"},
    {"t = %.2f s",
     "t = %.2f с"},
    {"texture",
     "текстура"},
    {"volume (dynamic); direct light stays realtime",
     "объём проб (для динамики); прямой свет остаётся реального времени"},
    {"w or h = 0 — the whole file",
     "ширина или высота 0 — весь файл"},
    {"warning",
     "предупреждение"},
    {"warnings",
     "предупреждения"},
    {"warnings (many)",
     "предупреждений"},
    {"yes",
     "да"},
    {"yesterday",
     "вчера"},
    {"| GPU %.2f ms",
     "| GPU %.2f мс"},
    {"| active: %s",
     "| активен: %s"},
    {"| lines: %d | %s",
     "| строк: %d | %s"},
    {"| no GPU timers",
     "| таймеров GPU нет"},
};
