// СГЕНЕРИРОВАНО scripts/gen_lang.py из editor/lang/ru.json — не править руками.
// Правки вносятся в JSON, затем: python3 scripts/gen_lang.py
//
// Язык: Русский. Строк: 1127.
struct TranslationPair {
    const char* Key;
    const char* Value;
};

constexpr TranslationPair kRussianStrings[] = {
    {"\nCtrl+Z undoes this.",
     "\nОтменить можно через Ctrl+Z."},
    {"\nTogether with its children that is ",
     "\nВместе с потомками это "},
    {"   ·   the folder is gone",
     "   ·   папки больше нет"},
    {"  (off)",
     "  (выключена)"},
    {" (with maps)",
     " (с картами)"},
    {" and ",
     " и ещё "},
    {" companion file(s))",
     " спутник(ов))"},
    {" d ago",
     " дн назад"},
    {" entities.",
     " сущностей."},
    {" h ago",
     " ч назад"},
    {" mo ago",
     " мес назад"},
    {" — details in Console",
     " — подробности в Console"},
    {"%.1f GiB",
     "%.1f ГиБ"},
    {"%.1f KiB",
     "%.1f КиБ"},
    {"%.1f MiB",
     "%.1f МиБ"},
    {"%llu B",
     "%llu Б"},
    {"%s -> %s (%.1fx smaller)",
     "%s -> %s (%.1fx меньше)"},
    {"%zu selected — editing the primary one",
     "Выбрано %zu — правим первичный"},
    {"(no event)",
     "(событие не задано)"},
    {"(no light entities)",
     "(источников-сущностей нет)"},
    {"(no scenes yet)",
     "(сцен пока нет)"},
    {"(open a project to save)",
     "(откройте проект, чтобы сохранить)"},
    {"(or the file cannot be read — details in Console).",
     "(или файл не читается — подробности в Console)."},
    {"1:1",
     "1:1"},
    {"2 = analytic two-bone, more = FABRIK",
     "2 — аналитическое решение на две кости, больше — FABRIK"},
    {"; not found: ",
     "; не найдено: "},
    {"A button reports a command; here you say what it does. The interface itself knows nothing about the game.",
     "Кнопка сообщает команду; здесь записано, что она делает. Сам интерфейс про игру не знает ничего."},
    {"A file on disk — the change affects EVERY object using this material.",
     "Файл на диске — изменится у ВСЕХ объектов с этим материалом."},
    {"A file with this name already exists",
     "Файл с таким именем уже есть"},
    {"A line of text",
     "Строка текста"},
    {"A modular 3D engine: ECS, RHI, PBR, physics, scripting, UI.",
     "Модульный 3D-движок: ECS, RHI, PBR, физика, скриптинг, UI."},
    {"A name cannot contain / \\ : * ? \" < > |",
     "В имени нельзя использовать / \\ : * ? \" < > |"},
    {"A node with nothing but a rectangle",
     "Узел, у которого есть только прямоугольник"},
    {"A number the user can change: slider, checkbox, stepper",
     "Число, которое меняет человек: ползунок, галка, шаг"},
    {"A point light at the object's position. Its shadow costs six passes of geometry (one per cube face), so it is best left only to the lamps that have something to occlude.",
     "Точечный свет в позиции объекта. Тень стоит шести проходов геометрии (по грани куба), поэтому её лучше оставлять только тем лампам, у которых есть что затенять."},
    {"A project keeps scenes, assets and materials in one folder.",
     "Проект хранит сцены, ассеты и материалы в одной папке."},
    {"A subtree template: double-clicking in Assets places a copy into the scene.",
     "Заготовка-поддерево: двойной клик в Assets ставит копию в сцену."},
    {"AO Radius",
     "Радиус AO"},
    {"AO Strength",
     "Сила AO"},
    {"About SAGE",
     "О SAGE"},
    {"About SAGE...",
     "О SAGE…"},
    {"Accent color",
     "Цвет акцента"},
    {"Active",
     "Активен"},
    {"Add Component",
     "Добавить компонент"},
    {"Add Goal",
     "Добавить цель"},
    {"Add Part",
     "Добавить часть"},
    {"Add component",
     "Добавить компонент"},
    {"Add effect",
     "Добавить эффект"},
    {"Add link",
     "Добавить связь"},
    {"Add stop",
     "Добавить остановку"},
    {"Add the prefab as a child",
     "Добавить префаб дочерним объектом"},
    {"Add variable",
     "Добавить переменную"},
    {"Add via Entity > Create Light; type/params in Inspector",
     "Добавляется через Entity > Create Light; тип и параметры — в инспекторе"},
    {"Added to the material emissive. Above 1 gives a bloom halo.",
     "Прибавляется к свечению материала. Больше 1 — ореол (bloom)."},
    {"Added to the scene: ",
     "Добавлено в сцену: "},
    {"Advanced",
     "Дополнительно"},
    {"Affects hit test",
     "Влияет на попадание"},
    {"Aim (look-at)",
     "Прицеливание (взгляд на цель)"},
    {"Aim Axis",
     "Ось прицеливания"},
    {"Air",
     "Воздух"},
    {"Albedo",
     "Альбедо"},
    {"Align Normal",
     "Выровнять по нормали"},
    {"Align the selection to the primary object",
     "Выровнять выделенные по первичному"},
    {"Align to axis",
     "Выровнять по оси"},
    {"Aligned along axis ",
     "Выровнено по оси "},
    {"Alignment",
     "Выравнивание"},
    {"All at once (T): move + rotate + scale",
     "Всё сразу (T): перенос + поворот + масштаб"},
    {"All components already added",
     "Все компоненты уже добавлены"},
    {"All files",
     "Все файлы"},
    {"All panels are closed",
     "Все панели закрыты"},
    {"Allow none",
     "Можно ничего не выбирать"},
    {"Alpha threshold",
     "Порог прозрачности"},
    {"Already installed",
     "Уже установлен"},
    {"Ambient (hemisphere)",
     "Засветка (полусфера)"},
    {"Ambient Occlusion",
     "Затенение складок (AO)"},
    {"Ambient Occlusion (SSAO)",
     "Затенение складок (SSAO)"},
    {"Ambient occlusion, channel R. Empty means AO = 1.",
     "Ambient occlusion, канал R. Пусто — AO = 1."},
    {"Anchor (offset)",
     "Привязка (смещение)"},
    {"Anchor corner in parent fractions",
     "Угол якоря в долях родителя"},
    {"Anchor max",
     "Якорь: максимум"},
    {"Anchor min",
     "Якорь: минимум"},
    {"Anchors",
     "Якоря"},
    {"Angle",
     "Угол"},
    {"Angle Limit",
     "Предельный угол"},
    {"Animated Model",
     "Анимированная модель"},
    {"Appearance",
     "Оформление"},
    {"Applied on top of the material.",
     "Накладываются поверх материала."},
    {"Arc",
     "Дуга"},
    {"Argument",
     "Аргумент"},
    {"Arranges children automatically",
     "Сам расставляет детей"},
    {"Aspect Ratio",
     "Соотношение сторон"},
    {"Aspect mode",
     "Режим соотношения"},
    {"Aspect ratio",
     "Соотношение сторон"},
    {"Asset",
     "Ассет"},
    {"Assets",
     "Ассеты"},
    {"Assets -> Import...",
     "Assets -> Импорт…"},
    {"Assign the material to this object",
     "Назначить материал этому объекту"},
    {"Atlas",
     "Атлас"},
    {"Atlas size",
     "Размер атласа"},
    {"Attach the script to this object",
     "Прикрепить скрипт к этому объекту"},
    {"Auto size",
     "Автоподбор кегля"},
    {"Auto-scroll",
     "Автопрокрутка"},
    {"Average",
     "Усреднять"},
    {"Axis",
     "Ось"},
    {"Azimuth",
     "Азимут"},
    {"Backdrop",
     "Подложка"},
    {"Background of the node",
     "Подложка узла"},
    {"Background surface",
     "Панель-подложка"},
    {"Bake GI",
     "Запечь GI"},
    {"Bake Probe",
     "Снять зонд"},
    {"Baked into the mesh on load — affects editor and built game",
     "Запекается в меш при загрузке — влияет и на редактор, и на собранную игру"},
    {"Baked: %d entities, %d page(s), probes %dx%dx%d",
     "Запечено: сущностей %d, страниц %d, проб %dx%dx%d"},
    {"Bakes indirect light to lightmaps (static) and a probe",
     "Запекает непрямой свет в лайтмапы (для статики) и в объём проб"},
    {"Base colour. Multiplied by the Albedo above.",
     "Базовый цвет. Умножается на Albedo выше."},
    {"Basic",
     "Основное"},
    {"Below this opacity the node stops catching the pointer",
     "Ниже этой прозрачности узел перестаёт ловить мышь"},
    {"Blend Time",
     "Время перехода"},
    {"Blend mode",
     "Режим наложения"},
    {"Block raycast",
     "Задерживать клики"},
    {"Bloom",
     "Ореол (bloom)"},
    {"Bloom Intensity",
     "Сила ореола"},
    {"Bloom Threshold",
     "Порог ореола"},
    {"Blur",
     "Размытие"},
    {"Blur what is behind the node instead of the node itself",
     "Размывать то, что позади узла, а не сам узел"},
    {"Body Type",
     "Тип тела"},
    {"Bone",
     "Кость"},
    {"Border",
     "Рамка"},
    {"Borderless",
     "Без рамки"},
    {"Bounces",
     "Переотражений"},
    {"Bounds of the selection",
     "Габариты выделенного"},
    {"Box",
     "Коробка"},
    {"Box Half Extents",
     "Полуразмеры коробки"},
    {"Box Parallax",
     "Поправка на коробку"},
    {"Brightness",
     "Яркость"},
    {"Bring a file into the project",
     "Внести файл в проект"},
    {"Broken references: ",
     "Битых ссылок: "},
    {"Brought in: ",
     "Внесено: "},
    {"Brought into the project: ",
     "Внесено в проект: "},
    {"Browse",
     "Обзор"},
    {"Browse...",
     "Обзор…"},
    {"Build",
     "Собрать"},
    {"Build Game",
     "Сборка игры"},
    {"Build Game...",
     "Собрать игру…"},
    {"Built: %s",
     "Собрано: %s"},
    {"Burst Count",
     "Частиц в залпе"},
    {"Burst Interval",
     "Интервал залпов"},
    {"Button",
     "Кнопка"},
    {"CPU, ms",
     "CPU, мс"},
    {"Call on object",
     "Позвать у объекта"},
    {"Camera",
     "Камера"},
    {"Camera inside this box uses this probe",
     "Камера внутри этой коробки использует этот зонд"},
    {"Cancel",
     "Отмена"},
    {"Cannot nest a node inside itself",
     "Нельзя вложить узел сам в себя"},
    {"Canvas zoom (wheel over the canvas)",
     "Масштаб холста (колесо над холстом)"},
    {"Capsule",
     "Капсула"},
    {"Capture prefab overrides",
     "Запомнить отличия экземпляра"},
    {"Captures the scene around this point into a cubemap",
     "Снимает окружение вокруг этой точки в кубическую карту"},
    {"Casts shadows",
     "Отбрасывает тени"},
    {"Catalog loaded, templates:",
     "Каталог загружен, шаблонов:"},
    {"Catalog:",
     "Каталог:"},
    {"Cell size",
     "Размер ячейки"},
    {"Chain Length",
     "Длина цепочки"},
    {"Channel",
     "Канал"},
    {"Channel R. Multiplied by the Metallic factor above.",
     "Канал R. Умножается на фактор Metallic выше."},
    {"Channel R. Multiplied by the Roughness factor above.",
     "Канал R. Умножается на фактор Roughness выше."},
    {"Character Controller",
     "Контроллер персонажа"},
    {"Checkbox",
     "Галочка"},
    {"Choose a folder",
     "Выберите папку"},
    {"Choose a material",
     "Выбрать материал"},
    {"Choose a model",
     "Выбрать модель"},
    {"Choose a project folder",
     "Выберите папку проекта"},
    {"Choose a script",
     "Выбрать скрипт"},
    {"Choose a template file",
     "Выберите файл шаблона"},
    {"Choose folder",
     "Выбрать папку"},
    {"Clear",
     "Очистить"},
    {"Clear bake",
     "Стереть запечённое"},
    {"Clear the console",
     "Очистить консоль"},
    {"Click — show in Assets",
     "Клик — показать в Assets"},
    {"Clicks outside the mask do not reach the subtree",
     "Клики вне маски не доходят до поддерева"},
    {"Close",
     "Закрыть"},
    {"Cloud Bottom",
     "Низ облаков"},
    {"Cloud Density",
     "Плотность облаков"},
    {"Cloud Steps",
     "Шагов сквозь облака"},
    {"Cloud Top",
     "Верх облаков"},
    {"Clouds",
     "Облака"},
    {"Code",
     "Код"},
    {"Collapse",
     "Свернуть повторы"},
    {"Collider",
     "Коллайдер"},
    {"Collider (C): drag the collision shape",
     "Коллайдер (C): тянуть форму столкновения"},
    {"Color",
     "Цвет"},
    {"Color adjust",
     "Цветокоррекция"},
    {"Colour",
     "Цвет"},
    {"Columns",
     "Столбцов"},
    {"Command",
     "Команда"},
    {"Commands",
     "Команды"},
    {"Compose",
     "Композиция"},
    {"Compound parts: %d",
     "Частей составного тела: %d"},
    {"Cone",
     "Конус"},
    {"Cone Half Angle",
     "Полуугол конуса"},
    {"Console",
     "Консоль"},
    {"Constraints",
     "Ограничения"},
    {"Containers",
     "Контейнеры"},
    {"Continue",
     "Продолжить"},
    {"Continuous",
     "Непрерывно"},
    {"Contrast",
     "Контраст"},
    {"Conversion failed: ",
     "Конвертация не удалась: "},
    {"Convert the whole folder to engine formats",
     "Конвертировать всю папку в форматы движка"},
    {"Convert to .sagemesh",
     "Конвертировать в .sagemesh"},
    {"Convert to .sagetex",
     "Конвертировать в .sagetex"},
    {"Converted %zu, skipped %zu; %.1f -> %.1f KB",
     "Сконвертировано %zu, пропущено %zu; %.1f -> %.1f КБ"},
    {"Copy",
     "Копировать"},
    {"Copy an outside file into the current project folder.\nA model moves together with its .mtl/.bin files and textures.",
     "Скопировать файл со стороны в текущую папку проекта.\nМодель переезжает вместе со своими .mtl/.bin и текстурами."},
    {"Copy path",
     "Копировать путь"},
    {"Copy report",
     "Копировать отчёт"},
    {"Copy the visible lines to the clipboard",
     "Скопировать видимые строки в буфер обмена"},
    {"Corner radius",
     "Скругление углов"},
    {"Could not copy the project file: ",
     "Не удалось скопировать файл проекта: "},
    {"Could not copy: ",
     "Не удалось скопировать: "},
    {"Could not create the folder: ",
     "Не удалось создать папку: "},
    {"Could not read the UI document",
     "Документ интерфейса прочитать не удалось"},
    {"Could not save sage.cfg",
     "Не удалось сохранить sage.cfg"},
    {"Could not write the game package",
     "Не удалось записать пакет игры"},
    {"Could not write the theme file",
     "Файл темы записать не удалось"},
    {"Coverage",
     "Облачность"},
    {"Crash report copied to the clipboard",
     "Отчёт о падении скопирован в буфер обмена"},
    {"Create",
     "Создать"},
    {"Create Animated Model",
     "Создать анимированную модель"},
    {"Create Asset",
     "Создать ассет"},
    {"Create Camera",
     "Создать камеру"},
    {"Create Child",
     "Создать потомка"},
    {"Create Cube",
     "Создать куб"},
    {"Create Decal",
     "Создать наклейку"},
    {"Create Empty",
     "Создать пустой объект"},
    {"Create Light",
     "Создать свет"},
    {"Create Particle Emitter",
     "Создать эмиттер частиц"},
    {"Create Physics Cube",
     "Создать физический куб"},
    {"Create Primitive",
     "Создать примитив"},
    {"Create UI",
     "Создать элемент интерфейса"},
    {"Create a project on the right — it will appear here and open in one click.",
     "Создайте проект справа — он появится здесь и будет открываться одним щелчком."},
    {"Create a sun",
     "Создать солнце"},
    {"Create material",
     "Создать материал"},
    {"Creates <Location>/<Name>/project.sageproj + scenes/ + assets/",
     "Создаст <Папка>/<Имя>/project.sageproj + scenes/ + assets/"},
    {"Creates a .sagemat next to the project assets and moves the current colour of this object into it.",
     "Создаёт .sagemat в ассетах проекта и переносит в него текущий цвет этого объекта."},
    {"Cross axis",
     "Поперечная ось"},
    {"Ctrl+D duplicates a line, Alt+Up/Down moves it.",
     "Ctrl+D — дублировать строку, Alt+Up/Down — переставить строку."},
    {"Ctrl+S saves, Ctrl+F finds, Ctrl+/ comments,",
     "Ctrl+S — сохранить, Ctrl+F — найти, Ctrl+/ — комментарий,"},
    {"Cube",
     "Куб"},
    {"Cursor",
     "Курсор"},
    {"Custom Shader",
     "Свой шейдер"},
    {"Custom shader for this node",
     "Свой шейдер для этого узла"},
    {"Cylinder",
     "Цилиндр"},
    {"Damping",
     "Затухание"},
    {"Data from a component this build does not have — kept as is",
     "Данные компонента, которого нет в этой сборке, — сохраняются как есть"},
    {"Debug",
     "Отладка"},
    {"Debug: sun visibility",
     "Отладка: видимость солнца"},
    {"Decal",
     "Наклейка"},
    {"Default",
     "По умолчанию"},
    {"Delete",
     "Удалить"},
    {"Delete \"%s\"?",
     "Удалить «%s»?"},
    {"Delete Asset",
     "Удалить ассет"},
    {"Delete report",
     "Удалить отчёт"},
    {"Delete the selected objects (",
     "Удалить выделенные объекты ("},
    {"Delete «",
     "Удалить «"},
    {"Deleting an object",
     "Удаление объекта"},
    {"Demo Segments",
     "Сегментов демо-модели"},
    {"Density",
     "Плотность"},
    {"Dir Max",
     "Направление, максимум"},
    {"Dir Min",
     "Направление, минимум"},
    {"Direction",
     "Направление"},
    {"Directional (sun)",
     "Направленный (солнце)"},
    {"Disc Colour",
     "Цвет диска"},
    {"Disc Size",
     "Размер диска"},
    {"Display",
     "Дисплей"},
    {"Displays a value; does not let the user change it",
     "Показывает значение и не даёт его менять"},
    {"Distance",
     "Дистанция"},
    {"Do not ask about this action again",
     "Больше не спрашивать об этом действии"},
    {"Document",
     "Документ"},
    {"Documents of one scene are drawn in this order: the pause menu must lie over the HUD regardless of which object was created first.",
     "Документы одной сцены рисуются в этом порядке: меню паузы обязано лечь поверх худа независимо от того, кого создали раньше."},
    {"Double-click a .lua, .vert, .frag or .glsl file in Assets to open it here.",
     "Двойной клик по .lua, .vert, .frag или .glsl в панели Assets открывает файл здесь."},
    {"Download",
     "Скачать"},
    {"Download and install",
     "Скачать и установить"},
    {"Drag an asset here",
     "Перетащите ассет сюда"},
    {"Drag an object from Hierarchy. The link holds the object's\nid, so renaming it does not break anything.",
     "Перетащите объект из дерева. Ссылка держится за номер\nобъекта, поэтому переименование её не ломает."},
    {"Draggable",
     "Можно тащить"},
    {"Draw Calls",
     "Вызовов"},
    {"Drives",
     "Диски"},
    {"Drop onto the surface (End)",
     "Опустить на поверхность (End)"},
    {"Drop shadow",
     "Падающая тень"},
    {"Dropdown",
     "Выпадающий список"},
    {"Dropped onto the surface: ",
     "Опущено на поверхность: "},
    {"Duplicate",
     "Дублировать"},
    {"Dynamic",
     "Динамическое"},
    {"Dynamic falls under gravity; Static/Kinematic don't",
     "Динамическое падает под гравитацией; статическое и кинематическое — нет"},
    {"Each icon at the sizes it is actually used at.",
     "Каждая иконка на тех размерах, на которых она и работает."},
    {"Each part of the model has its own material. Empty means the object material above.",
     "У каждой части модели свой материал. Пусто — красится материалом объекта выше."},
    {"Each view is a full scene pass",
     "Каждый вид — полный проход сцены"},
    {"Edit",
     "Правка"},
    {"Edit document",
     "Править документ"},
    {"Editable number",
     "Изменяемое число"},
    {"Editable text",
     "Изменяемый текст"},
    {"Editable text with a caret",
     "Изменяемый текст с кареткой"},
    {"Edited in the object inspector; direction is its rotation",
     "Правится в инспекторе объекта; направление — его поворот"},
    {"Edits apply live to every entity using this material.",
     "Правки применяются сразу ко всем объектам с этим материалом."},
    {"Effects",
     "Эффекты"},
    {"Elastic",
     "Упругая граница"},
    {"Elevation",
     "Высота над горизонтом"},
    {"Emissive",
     "Свечение"},
    {"Emissive Strength",
     "Сила свечения"},
    {"Emissive multiplier. Values above 1 produce a bloom halo.",
     "Множитель свечения. Значения больше 1 дают ореол (bloom)."},
    {"Empty",
     "Пусто"},
    {"Empty node",
     "Пустой узел"},
    {"Empty path = procedural demo (\"tentacle\")",
     "Пустой путь — процедурное демо («щупальце»)"},
    {"Enable Fog",
     "Включить туман"},
    {"Enable Skybox",
     "Включить небо"},
    {"Enabled",
     "Включено"},
    {"End Color",
     "Конечный цвет"},
    {"Enter a file name",
     "Укажите имя файла"},
    {"Enter a project name",
     "Введите имя проекта"},
    {"Entities: %zu",
     "Объектов: %zu"},
    {"Entity",
     "Объект"},
    {"Environment",
     "Среда"},
    {"Environment: sky, air, ambient light (saved with the scene)",
     "Среда: небо, воздух, окружающий свет (хранится в сцене)"},
    {"Equal to min means a point anchor; different means stretch",
     "Совпал с минимумом — точка; разошёлся — растяжение"},
    {"Error (%d)",
     "Ошибки (%d)"},
    {"Event",
     "Событие"},
    {"Everyone subscribed to this name hears it: scripts and\nengine code alike.",
     "Его услышат все, кто подписан на это имя: и скрипты,\nи код движка."},
    {"Everything in the editor works inside a project: asset paths, building the game, templates.",
     "Всё в редакторе работает внутри проекта: пути к ассетам, сборка игры, шаблоны."},
    {"Exit",
     "Выход"},
    {"Export theme to themes/...",
     "Выгрузить тему в themes/..."},
    {"Exposure",
     "Экспозиция"},
    {"FOV",
     "Угол обзора"},
    {"FPS",
     "Кадр/с"},
    {"Failed to load: %s",
     "Не загрузилась: %s"},
    {"Failed to open the project: ",
     "Проект не открылся: "},
    {"Far",
     "Дальняя плоскость"},
    {"Far Clip",
     "Дальняя плоскость"},
    {"File",
     "Файл"},
    {"File cannot be read",
     "Файл не читается"},
    {"File name",
     "Имя файла"},
    {"File not found",
     "Файл не найден"},
    {"File not found: ",
     "Файл не найден: "},
    {"File outside the project",
     "Файл вне проекта"},
    {"File reference",
     "Ссылка на файл"},
    {"Files brought into the project: ",
     "Внесено в проект файлов: "},
    {"Fill",
     "Заливка"},
    {"Fill color",
     "Цвет заполнения"},
    {"Find",
     "Найти"},
    {"Find (Enter for next)",
     "Найти (Enter — следующее)"},
    {"Fit",
     "Вписать"},
    {"Fit height",
     "Высота по содержимому"},
    {"Fit width",
     "Ширина по содержимому"},
    {"Fixed",
     "Жёсткий"},
    {"Fixed corners in source pixels",
     "Неподвижные углы в пикселях исходника"},
    {"Flip X",
     "Отразить по X"},
    {"Flip Y",
     "Отразить по Y"},
    {"Focus",
     "Фокус"},
    {"Focus group",
     "Группа фокуса"},
    {"Focusable",
     "Принимает фокус"},
    {"Fog",
     "Туман"},
    {"Fog Color",
     "Цвет тумана"},
    {"Fog End",
     "Конец тумана"},
    {"Fog Start",
     "Начало тумана"},
    {"Folder",
     "Папка"},
    {"Folders",
     "Папки"},
    {"Font",
     "Шрифт"},
    {"Foot Lock",
     "Фиксация стоп"},
    {"Forward Scattering",
     "Рассеяние вперёд"},
    {"Found file: %s",
     "Найден файл: %s"},
    {"Four views",
     "Четыре вида"},
    {"Fragment",
     "Фрагментный"},
    {"Frame Cap (0=off)",
     "Предел кадров (0 — без предела)"},
    {"Frame the selection (F)",
     "Показать в кадре (F)"},
    {"Frame, drop, align",
     "Кадрировать, посадить, выровнять"},
    {"Frame: CPU %.2f ms",
     "Кадр: CPU %.2f мс"},
    {"Free",
     "Свободное"},
    {"Friction",
     "Трение"},
    {"From disk",
     "С диска"},
    {"Front",
     "Спереди"},
    {"Fullscreen",
     "Полноэкранный"},
    {"GB",
     "ГБ"},
    {"GI Static",
     "Статика для GI"},
    {"GI: bake finished — save the scene to write the lightmaps",
     "GI: бейк завершён — сохрани сцену, чтобы записать лайтмапы"},
    {"GI: entities marked static: ",
     "GI: помечено статичными сущностей: "},
    {"GI: no static entities — add the GI Static component",
     "GI: нет статичных сущностей — добавь компонент GI Static"},
    {"GI: the scene changed during the bake — the result was dropped",
     "GI: сцена изменилась во время бейка — результат отброшен"},
    {"GPU, ms",
     "GPU, мс"},
    {"Game",
     "Игра"},
    {"Game (view from the game camera)",
     "Игра (вид из игровой камеры)"},
    {"Game Settings",
     "Настройки игры"},
    {"Game Settings...",
     "Настройки игры..."},
    {"Game Settings: quality and cost of the frame (saved with the project)",
     "Настройки игры: качество и цена кадра (хранятся в проекте)"},
    {"Game panel renders from the first Primary camera",
     "Панель Game рисует от первой камеры с флагом Primary"},
    {"Gamma",
     "Гамма"},
    {"Gap",
     "Зазор"},
    {"Gizmo axes: object",
     "Оси гизмо: объекта"},
    {"Gizmo axes: object or world",
     "Оси гизмо: объекта или мира"},
    {"Gizmo axes: world",
     "Оси гизмо: мира"},
    {"Gizmo: move, rotate, scale",
     "Гизмо: перенос, поворот, масштаб"},
    {"Global Illumination (baked)",
     "Глобальное освещение (запечённое)"},
    {"Glow",
     "Свечение"},
    {"Gradient",
     "Градиент"},
    {"Gradient angle",
     "Угол градиента"},
    {"Gradient end",
     "Конец градиента"},
    {"Gradient start",
     "Начало градиента"},
    {"Graphics",
     "Графика"},
    {"Gravity",
     "Гравитация"},
    {"Grid",
     "Сетка"},
    {"Grid and bounds of the selection",
     "Сетка и габариты выделения"},
    {"Grid cell",
     "Клетка сетки"},
    {"Ground",
     "Земля"},
    {"Grounded: %s",
     "На земле: %s"},
    {"Group",
     "Группа"},
    {"Half Extents",
     "Полуразмеры"},
    {"Half Height",
     "Полувысота"},
    {"Handle size",
     "Размер ручки"},
    {"Height",
     "Высота"},
    {"Height Falloff",
     "Спад с высотой"},
    {"Height mode",
     "Режим высоты"},
    {"Help",
     "Справка"},
    {"Hidden",
     "Скрытые"},
    {"Hidden hint panel on a high layer",
     "Спрятанная подсказка на верхнем слое"},
    {"Hide or show",
     "Скрыть или показать"},
    {"Hierarchy",
     "Иерархия"},
    {"High",
     "Высокие"},
    {"Hinge",
     "Шарнир"},
    {"Hit padding",
     "Расширение области попадания"},
    {"Hit shape",
     "Форма попадания"},
    {"Hit test",
     "Попадание"},
    {"Horizontal",
     "По горизонтали"},
    {"Horizontal align",
     "Выравнивание по горизонтали"},
    {"Hotkeys keep working for hidden tools",
     "Горячие клавиши скрытых инструментов работают"},
    {"How hard the character pushes dynamic bodies",
     "С какой силой персонаж толкает динамические тела"},
    {"How tall a step the character climbs without jumping",
     "На какую ступеньку персонаж взбирается без прыжка"},
    {"How this mask combines with the parent masks",
     "Как маска складывается с масками предков"},
    {"IK",
     "Обратная кинематика"},
    {"IK Enabled",
     "Включить ОК"},
    {"Icon",
     "Значок"},
    {"Icon name",
     "Имя значка"},
    {"Icon sheet",
     "Страница иконок"},
    {"Id (folder name)",
     "Идентификатор (имя папки)"},
    {"Id: %d",
     "Номер: %d"},
    {"Ignore layout",
     "Вне раскладки"},
    {"Image",
     "Картинка"},
    {"Images",
     "Изображения"},
    {"Import Scale",
     "Масштаб при импорте"},
    {"Import failed: ",
     "Импорт не удался: "},
    {"Import settings are baked into the mesh on load.",
     "Настройки импорта запекаются в меш при загрузке."},
    {"Import...",
     "Импорт…"},
    {"Import: ",
     "Импорт: "},
    {"In characters, not bytes",
     "В символах, а не в байтах"},
    {"Index",
     "Номер"},
    {"Index of the selected child — tabs, radio groups",
     "Номер выбранного ребёнка: вкладки, переключатели"},
    {"Info",
     "Сведения"},
    {"Inner",
     "Внутрь"},
    {"Inner Cone",
     "Внутренний конус"},
    {"Inner shadow",
     "Внутренняя тень"},
    {"Input",
     "Поле ввода"},
    {"Input field",
     "Поле ввода"},
    {"Inset",
     "Отступ рамки"},
    {"Insets used when the axis is stretched",
     "Поля, когда ось растянута"},
    {"Inspector",
     "Инспектор"},
    {"Install",
     "Установка"},
    {"Install .sagetemplate file...",
     "Установить файл .sagetemplate..."},
    {"Install from a project folder...",
     "Установить из папки проекта..."},
    {"Installed",
     "Установленные"},
    {"Instance overrides",
     "Поправки экземпляра"},
    {"Intensity",
     "Яркость"},
    {"Intensity %.2f, direction (%.2f, %.2f, %.2f)",
     "Яркость %.2f, направление (%.2f, %.2f, %.2f)"},
    {"Interaction",
     "Взаимодействие"},
    {"Interactive",
     "Интерактивный"},
    {"Interface",
     "Интерфейс"},
    {"Interface editor: the game frame at its own resolution",
     "Редактор интерфейса: игровой кадр в его собственном разрешении"},
    {"Interface language changed",
     "Язык интерфейса изменён"},
    {"Interface scale",
     "Масштаб интерфейса"},
    {"Invert",
     "Инвертировать"},
    {"It did not overwrite your scene — this is a separate copy.",
     "Он не перезаписывал вашу сцену — это отдельная копия."},
    {"Italic",
     "Курсив"},
    {"Joint",
     "Сочленение"},
    {"KB",
     "КБ"},
    {"Keep the file",
     "Оставить файл"},
    {"Kind of the argument",
     "Вид аргумента"},
    {"Kind of the value",
     "Вид значения"},
    {"Kinematic",
     "Кинематическое"},
    {"LMB orbits, wheel zooms",
     "ЛКМ — вращать, колесо — приблизить"},
    {"Label",
     "Подпись"},
    {"Landed on nothing: there is no geometry under the box, or it faces away from the decal.",
     "Ни на что не легла: под коробкой нет геометрии, либо она отвёрнута от наклейки."},
    {"Language",
     "Язык"},
    {"Layer",
     "Слой"},
    {"Layer → order → tree position",
     "Слой → порядок → место в дереве"},
    {"Layout",
     "Положение"},
    {"Left, top, right, bottom",
     "Слева, сверху, справа, снизу"},
    {"Legacy",
     "Устаревшее"},
    {"Letter spacing",
     "Межбуквенный интервал"},
    {"Light",
     "Свет"},
    {"Light Shafts",
     "Лучи света"},
    {"Light halo around the visible shape",
     "Ореол вокруг видимой формы"},
    {"Lightmapped",
     "С лайтмапой"},
    {"Limits the whole subtree to a shape",
     "Ограничивает всё поддерево формой"},
    {"Line",
     "Строка"},
    {"Line %d, column %d  |  lines: %zu  |  %s  |  %s",
     "Строка %d, столбец %d  |  строк: %zu  |  %s  |  %s"},
    {"Line spacing",
     "Межстрочный интервал"},
    {"Linear distance fog (applied in Shaded mode)",
     "Линейный туман по дальности (виден в режиме Shaded)"},
    {"List",
     "Список"},
    {"Lit by object: %s",
     "Светит объект: %s"},
    {"Load",
     "Загрузить"},
    {"Localization key",
     "Ключ перевода"},
    {"Location",
     "Папка"},
    {"Lock: not selectable on the canvas",
     "Замок: не выделяется на холсте"},
    {"Locked",
     "Заперт"},
    {"Loop",
     "Зациклить"},
    {"Low",
     "Низкие"},
    {"Low — weak/old PCs: no shadows or post-processing, 75%% render scale\nMedium — 1024 shadows + tone mapping, no Bloom/SSAO\nHigh — everything on, 2048 shadows (default)\nUltra — 4096 shadows + MSAA 4x\nIn game: environment variable SAGE_QUALITY=low|medium|high|ultra",
     "Low — слабые/старые ПК: без теней и пост-процесса, рендер 75%%\nMedium — тени 1024 + тон-маппинг, без Bloom/SSAO\nHigh — всё включено, тени 2048 (по умолчанию)\nUltra — тени 4096 + MSAA 4x\nВ игре: переменная окружения SAGE_QUALITY=low|medium|high|ultra"},
    {"MB",
     "МБ"},
    {"MSAA",
     "Сглаживание MSAA"},
    {"Main axis",
     "Основная ось"},
    {"Map value multiplies the factor above; Enter applies the path.",
     "Значение карты множится на коэффициент выше; Enter применяет путь."},
    {"Margin",
     "Поля"},
    {"Mark static geometry",
     "Пометить статичную геометрию"},
    {"Mark the area without actually clipping",
     "Пометить область, не обрезая"},
    {"Mask",
     "Маска"},
    {"Mask texture",
     "Картинка маски"},
    {"Masked, scrollable area",
     "Прокручиваемая область с маской"},
    {"Mass",
     "Масса"},
    {"Material",
     "Материал"},
    {"Material assigned: ",
     "Материал назначен: "},
    {"Material cannot be read",
     "Материал не читается"},
    {"Material created: ",
     "Материал создан: "},
    {"Materials (*.sagemat)",
     "Материалы (*.sagemat)"},
    {"Materials (.sagemat) and models (.obj/.gltf/.glb)",
     "Материалы (.sagemat) и модели (.obj/.gltf/.glb)"},
    {"Max",
     "Максимум"},
    {"Max Angle",
     "Максимальный угол"},
    {"Max Distance",
     "Максимальная дистанция"},
    {"Max Slope",
     "Максимальный уклон"},
    {"Max length",
     "Предел длины"},
    {"Max lines",
     "Предел строк"},
    {"Max size",
     "Максимальный размер"},
    {"Medium",
     "Средние"},
    {"Mem",
     "Память"},
    {"Mesh",
     "Меш"},
    {"Mesh Renderer",
     "Отрисовка меша"},
    {"Mesh not loaded",
     "Меш не загружен"},
    {"Mesh replaced: ",
     "Меш заменён: "},
    {"Metallic",
     "Металличность"},
    {"Method",
     "Метод"},
    {"Min",
     "Минимум"},
    {"Min Distance",
     "Минимальная дистанция"},
    {"Min size",
     "Минимальный размер"},
    {"Mode",
     "Режим"},
    {"Model",
     "Модель"},
    {"Model (.glb)",
     "Модель (.glb)"},
    {"Model material: ",
     "Материал модели: "},
    {"Model materials imported: ",
     "Материалов модели импортировано: "},
    {"Model parts",
     "Части модели"},
    {"Models",
     "Модели"},
    {"Models and images in this folder (including nested) -> .sagemesh/.sagetex.\nAlready converted files are skipped, sources stay in place.",
     "Модели и картинки этой папки (включая вложенные) -> .sagemesh/.sagetex.\nУже сконвертированные пропускаются, исходники остаются."},
    {"Moon",
     "Луна"},
    {"Moon colour",
     "Цвет луны"},
    {"Moon size",
     "Размер луны"},
    {"Move (W)",
     "Перенос (W)"},
    {"Move down",
     "Ниже"},
    {"Move up",
     "Выше"},
    {"Moved into ",
     "Перенесено в "},
    {"Moving failed: ",
     "Перенос не удался: "},
    {"Multiline",
     "В несколько строк"},
    {"Multiplies the material albedo. White means as in the material.",
     "Множится на albedo материала. Белый — как в материале."},
    {"Multiplies the material opacity.",
     "Множится на непрозрачность материала."},
    {"NEW PROJECT",
     "НОВЫЙ ПРОЕКТ"},
    {"Name",
     "Имя"},
    {"Name in the list",
     "Название в списке"},
    {"Named style from the theme",
     "Именованный стиль из темы"},
    {"Nav down",
     "Навигация: вниз"},
    {"Nav left",
     "Навигация: влево"},
    {"Nav right",
     "Навигация: вправо"},
    {"Nav up",
     "Навигация: вверх"},
    {"Navigation",
     "Навигация"},
    {"Near",
     "Ближняя плоскость"},
    {"Needs a %s",
     "Нужен: %s"},
    {"Needs a Rigid Body; only the Jolt backend simulates joints",
     "Нужно твёрдое тело; суставы считает только бэкенд Jolt"},
    {"Needs an offscreen target — the cost is visible in the profiler",
     "Нужна промежуточная цель — стоимость видна в профайлере"},
    {"Negative means take the radius from the fill",
     "Отрицательное — взять скругление у заливки"},
    {"Net Replicated",
     "Сетевая репликация"},
    {"New",
     "Создать"},
    {"New Folder",
     "Новая папка"},
    {"New Material (.sagemat)",
     "Новый материал (.sagemat)"},
    {"New Project",
     "Новый проект"},
    {"New Project...",
     "Новый проект…"},
    {"New Scene",
     "Новая сцена"},
    {"New Script (.lua)",
     "Новый скрипт (.lua)"},
    {"New Text File (.txt)",
     "Новый текстовый файл (.txt)"},
    {"New name",
     "Новое имя"},
    {"Nine-slice",
     "Девятина"},
    {"No Animated Model - goals do nothing",
     "Нет анимированной модели — цели ни на что не влияют"},
    {"No animation clips (bind pose)",
     "Клипов анимации нет (поза привязки)"},
    {"No cover: the prefab has no visible geometry",
     "Обложки нет: в префабе не нашлось видимой геометрии"},
    {"No directional light in the scene — no sun. Direction, colour and intensity live on the object itself.",
     "В сцене нет направленного света — солнца нет. Направление, цвет и яркость задаются на самом объекте."},
    {"No file",
     "Файл не выбран"},
    {"No messages of the selected level",
     "Нет сообщений выбранного уровня"},
    {"No model assigned",
     "Модель не назначена"},
    {"No open files.",
     "Нет открытых файлов."},
    {"No public variables. A script declares them with a Vars\ntable; here you can add your own.",
     "Публичных переменных нет. Скрипт объявляет их таблицей\nVars; здесь можно добавить свои."},
    {"No ready-made projects installed yet. Get one on the «Download» tab, or install a .sagetemplate file from disk.",
     "Готовых проектов пока не установлено. Возьмите на вкладке «Скачать» или поставьте файл .sagetemplate с диска."},
    {"No script attached",
     "Скрипт не прикреплён"},
    {"No such file: ",
     "Файла нет: "},
    {"Node point that lands on the anchor and rotates in place",
     "Точка узла, которая ложится на якорь и вокруг которой идёт поворот"},
    {"Node reacts to pointer, keyboard and navigation",
     "Узел отвечает на мышь, клавиатуру и навигацию"},
    {"None",
     "Нет"},
    {"Normal map, tangent space (OpenGL: green is up).",
     "Карта нормалей, tangent-space (OpenGL: зелёный вверх)."},
    {"Normal: tangent-space (OpenGL). Metallic/Rough/AO use R channel.",
     "Нормали — в касательном пространстве (OpenGL). Металличность, шероховатость и AO берутся из канала R."},
    {"Normalize size (max side = 1)",
     "Нормировать размер (наибольшая сторона = 1)"},
    {"Not assigned",
     "Не назначен"},
    {"Not baked (%d static entities)",
     "Не запечено (статичных объектов: %d)"},
    {"Not the scene's sun: a directional light with a lower number in the hierarchy is already the sun, and only one takes part in the frame.",
     "Это не солнце сцены: солнцем уже работает направленный свет с меньшим номером в иерархии, а в кадре участвует только одно."},
    {"Nothing happens yet. A link lets this element send an event\nor call a method on another object by itself.",
     "Пока ничего не происходит. Связь позволяет элементу самому\nпослать событие или позвать метод у другого объекта."},
    {"Nothing here yet.",
     "Пока пусто."},
    {"Nothing matches the search.",
     "Ничего не найдено по запросу."},
    {"Nothing selected",
     "Ничего не выбрано"},
    {"Nothing to convert: no models or images in the folder",
     "Конвертировать нечего: в папке нет моделей и картинок"},
    {"Nothing — drag an object here",
     "Ничего — перетащите объект сюда"},
    {"Nowhere to drop the material — no object under the cursor",
     "Материал ронять некуда — под курсором нет объекта"},
    {"Number",
     "Число"},
    {"OPEN ANOTHER",
     "ОТКРЫТЬ ДРУГОЙ"},
    {"Object",
     "Объект"},
    {"Object is gone (id ",
     "Объекта больше нет (номер "},
    {"Object reference",
     "Ссылка на объект"},
    {"Objects",
     "Объектов"},
    {"Off",
     "Выключено"},
    {"Off lets clicks pass through to whatever is below",
     "Выключено — клики проходят насквозь"},
    {"Off: the document is visible but does not take the mouse — a HUD over the game must not eat shots.",
     "Выключено — документ виден, но мышь не ловит: худ поверх игры не должен съедать выстрелы."},
    {"Offset",
     "Смещение"},
    {"Only a model or a prefab can be added to the scene",
     "В сцену можно добавить модель или префаб"},
    {"Opacity",
     "Непрозрачность"},
    {"Open",
     "Открыть"},
    {"Open Project",
     "Открыть проект"},
    {"Open Project...",
     "Открыть проект…"},
    {"Open Scene",
     "Открыть сцену"},
    {"Open Scene...",
     "Открыть сцену…"},
    {"Open UI document",
     "Открыть документ интерфейса"},
    {"Open console",
     "Открыть консоль"},
    {"Open in editor",
     "Открыть в редакторе"},
    {"Open project",
     "Открыть проект"},
    {"Open scene",
     "Открыть сцену"},
    {"Open the copy",
     "Открыть копию"},
    {"Open the project folder",
     "Открыть папку проекта"},
    {"Open...",
     "Открыть..."},
    {"Option picker",
     "Выбор варианта"},
    {"Order",
     "Порядок"},
    {"Ordered stack of effects applied to the node",
     "Упорядоченный стек эффектов узла"},
    {"Outer Cone",
     "Внешний конус"},
    {"Outline",
     "Обводка"},
    {"Outline around the node",
     "Рамка вокруг узла"},
    {"Outline color",
     "Цвет обводки"},
    {"Outline width",
     "Толщина обводки"},
    {"Output dir",
     "Папка вывода"},
    {"Overflow",
     "Что не влезло"},
    {"Override the material",
     "Переопределить материал"},
    {"PAUSED",
     "ПАУЗА"},
    {"PBR",
     "PBR"},
    {"PLAYING",
     "ИГРА ИДЁТ"},
    {"Packages SagePlayer + project '%s' into a runnable game",
     "Упакует SagePlayer и проект «%s» в готовую к запуску игру"},
    {"Packs the open project into one .sagetemplate file — the same kind of file the editor installs. Editor sidecars (.meta) are left out: they describe a local import and are rebuilt anyway.",
     "Упаковывает открытый проект в один файл .sagetemplate — ровно такой, какие редактор и устанавливает. Сайдкары редактора (.meta) не кладутся: они описывают локальный импорт и всё равно перегенерируются."},
    {"Padding",
     "Внутренние поля"},
    {"Painted with the object material.",
     "Красится материалом объекта."},
    {"Panel",
     "Панель"},
    {"Paragraph spacing",
     "Интервал между абзацами"},
    {"Param 0",
     "Параметр 0"},
    {"Param 1",
     "Параметр 1"},
    {"Param 2",
     "Параметр 2"},
    {"Param 3",
     "Параметр 3"},
    {"Parameters",
     "Параметры"},
    {"Params: %d (edit in the .sagemat file)",
     "Параметров: %d (правятся в файле .sagemat)"},
    {"Part ",
     "Часть "},
    {"Particle Emitter",
     "Эмиттер частиц"},
    {"Parts override the single shape above",
     "Части заменяют одиночную форму выше"},
    {"Passes",
     "Проходов"},
    {"Password",
     "Пароль"},
    {"Path",
     "Путь"},
    {"Path copied to the clipboard",
     "Путь скопирован в буфер обмена"},
    {"Path to a .sage file (or double-click in the Assets panel)",
     "Путь к файлу .sage (или двойной клик в панели Assets)"},
    {"Path to project.sageproj or to a project folder",
     "Путь к project.sageproj или к папке проекта"},
    {"Pause",
     "Приостановить"},
    {"Per-frame numbers swing by tens of percent because of the OS scheduler.\nThe 30-frame average is what you actually read.\n\nGPU time lags three frames behind: asking for it right away means waiting\nfor the card, that is, creating the delay you are measuring.",
     "Покадровые значения скачут на десятки процентов от планировщика ОС.\nУсреднение по 30 кадрам — то, по чему и смотрят.\n\nВремя GPU отстаёт на три кадра: спросить его сразу значит дождаться\nвидеокарты, то есть своим измерением создать измеряемую задержку."},
    {"Percent",
     "Проценты"},
    {"Perspective",
     "Перспектива"},
    {"Pivot",
     "Точка привязки"},
    {"Pixel art",
     "Пиксель-арт"},
    {"Place in scene",
     "Поставить в сцену"},
    {"Placed in the scene: ",
     "Поставлено в сцену: "},
    {"Placeholder key",
     "Ключ подсказки поля"},
    {"Plane",
     "Плоскость"},
    {"Plant Height",
     "Высота постановки"},
    {"Play",
     "Играть"},
    {"Playing",
     "Проигрывается"},
    {"Point",
     "Точечный"},
    {"Pole",
     "Направляющая"},
    {"Polygon",
     "Многоугольник"},
    {"Position",
     "Позиция"},
    {"Position, rotation, scale, color and primitive are replicated",
     "Передаются позиция, поворот, масштаб, цвет и вид примитива"},
    {"Positioned by anchors even inside a layout container",
     "Стоит по якорям даже внутри контейнера раскладки"},
    {"Post-Process",
     "Пост-эффекты"},
    {"Post-Processing",
     "Пост-обработка"},
    {"Prefab instance",
     "Экземпляр префаба"},
    {"Prefab saved: ",
     "Префаб сохранён: "},
    {"Preset:",
     "Пресет:"},
    {"Press «Refresh» to fetch the list. Nothing is downloaded until you ask for it.",
     "Нажмите «Обновить», чтобы получить список. Ничего не скачивается, пока не попросите."},
    {"Preview",
     "Превью"},
    {"Previous session crashed",
     "Прошлый запуск завершился аварийно"},
    {"Primary",
     "Главная"},
    {"Probe cell size",
     "Шаг сетки проб"},
    {"Procedural gradient (top -> horizon), no textures",
     "Процедурный градиент (зенит -> горизонт), без текстур"},
    {"Procedural vector shape",
     "Процедурная векторная форма"},
    {"Profiler",
     "Профилировщик"},
    {"Progress",
     "Полоса"},
    {"Progress bar",
     "Полоса заполнения"},
    {"Project",
     "Проект"},
    {"Project Launcher...",
     "Окно проектов…"},
    {"Project Scenes",
     "Сцены проекта"},
    {"Project assets",
     "Ассеты проекта"},
    {"Project folder or .sageproj",
     "Папка проекта или .sageproj"},
    {"Project name",
     "Имя проекта"},
    {"Project templates",
     "Шаблоны проектов"},
    {"Project templates...",
     "Шаблоны проектов..."},
    {"Project:",
     "Проект:"},
    {"Projected triangles: %d",
     "Спроецировано треугольников: %d"},
    {"Projection goes along -Z; Scale sets the size",
     "Проекция идёт вдоль -Z; размер задаёт Scale"},
    {"Projection of the active view",
     "Проекция активного вида"},
    {"Projects (*.sageproj)",
     "Проекты (*.sageproj)"},
    {"Quality",
     "Качество"},
    {"Quality and cost of the frame — saved into the project as sage.cfg. The look of the scene (sky, fog, ambient) is in Environment; light sources are objects in the hierarchy.",
     "Качество и цена кадра — сохраняются в проект, в sage.cfg. Вид сцены (небо, туман, окружающий свет) — в окне «Среда»; источники света — объекты в иерархии."},
    {"RECENT",
     "НЕДАВНИЕ"},
    {"Radius",
     "Радиус"},
    {"Range",
     "Дальность"},
    {"Rate (p/s)",
     "Частота (частиц/с)"},
    {"Ray Steps",
     "Шагов по лучу"},
    {"Re-bake lighting after changes (Lighting panel)",
     "После правок освещение стоит перезапечь (панель Lighting)"},
    {"Re-read the document from disk",
     "Перечитать документ с диска"},
    {"Read only",
     "Только чтение"},
    {"Ready-made projects are content, not part of the editor: they are installed separately and can be removed. Built-in templates (empty, demo, menu) are built by code and are always available.",
     "Готовые проекты — это содержимое, а не часть редактора: они ставятся отдельно и удаляются. Встроенные шаблоны (пустой, демо, меню) собираются кодом и доступны всегда."},
    {"Realtime (re-capture every frame)",
     "В реальном времени (пересъёмка каждый кадр)"},
    {"Realtime = 6 scene passes per frame - use sparingly",
     "Реальное время — шесть проходов сцены на кадр, включайте с оглядкой"},
    {"Rebuild",
     "Пересобрать"},
    {"Recenter (AABB -> origin)",
     "Отцентровать (габарит -> начало координат)"},
    {"Rect (Y): drag the faces of the bounding box",
     "Рамка (Y): тянуть за грани габаритной коробки"},
    {"Redo",
     "Повторить"},
    {"Reflection Probe",
     "Зонд отражений"},
    {"Refresh",
     "Обновить"},
    {"Region in source pixels; zero size means the whole file",
     "Кусок в пикселях исходника; нулевой размер — весь файл"},
    {"Reimport",
     "Переимпортировать"},
    {"Reinstall",
     "Переустановить"},
    {"Release Time",
     "Время затухания"},
    {"Reload",
     "Перечитать"},
    {"Remove",
     "Убрать"},
    {"Remove Animated Model",
     "Убрать анимированную модель"},
    {"Remove Camera",
     "Убрать камеру"},
    {"Remove Character Controller",
     "Убрать контроллер персонажа"},
    {"Remove Collider",
     "Убрать коллайдер"},
    {"Remove Emitter",
     "Убрать эмиттер"},
    {"Remove Goal",
     "Убрать цель"},
    {"Remove IK",
     "Убрать обратную кинематику"},
    {"Remove Joint",
     "Убрать сустав"},
    {"Remove Light",
     "Убрать свет"},
    {"Remove Part",
     "Убрать часть"},
    {"Remove Reflection Probe",
     "Убрать зонд отражений"},
    {"Remove Rigid Body",
     "Убрать твёрдое тело"},
    {"Remove Script",
     "Убрать скрипт"},
    {"Remove component",
     "Убрать компонент"},
    {"Remove from the list (the project is not deleted)",
     "Убрать из списка (проект не удаляется)"},
    {"Remove the link",
     "Убрать связь"},
    {"Remove the variable",
     "Убрать переменную"},
    {"Rename",
     "Переименовать"},
    {"Rename Asset",
     "Переименовать ассет"},
    {"Render",
     "Рендер"},
    {"Render Scale",
     "Масштаб рендера"},
    {"Render Scale < 1 is faster; > 1 supersamples (sharper).",
     "Render Scale < 1 — быстрее; > 1 — суперсэмплинг (чётче)."},
    {"Render mode",
     "Режим отрисовки"},
    {"Repeat",
     "Повторять"},
    {"Replace this object's mesh",
     "Заменить меш этого объекта"},
    {"Reported to the game; the UI never interprets it",
     "Сообщается игре; интерфейс её не толкует"},
    {"Reports a click; the game decides what it means",
     "Сообщает о нажатии; что оно значит, решает игра"},
    {"Reports next to the editor: %d",
     "Отчётов рядом с редактором: %d"},
    {"Rescan project",
     "Пересканировать проект"},
    {"Reset Layout",
     "Сбросить раскладку"},
    {"Reset scale",
     "Обычный масштаб"},
    {"Reset to Defaults",
     "Вернуть значения по умолчанию"},
    {"Reset view",
     "Сбросить вид"},
    {"Resizable",
     "Изменяемый размер"},
    {"Resolution",
     "Разрешение"},
    {"Resolved through the game localization; text stays as a fallback",
     "Разрешается переводом игры; текст остаётся запасным"},
    {"Restitution",
     "Упругость"},
    {"Restore panels",
     "Вернуть панели"},
    {"Restore scene?",
     "Восстановить сцену?"},
    {"Resume",
     "Продолжить"},
    {"Reverse",
     "Обратный порядок"},
    {"Revert",
     "Откатить"},
    {"Right-click to create a folder, script, material or text file.",
     "Правый клик создаёт папку, скрипт, материал или текстовый файл."},
    {"Rigid Body",
     "Твёрдое тело"},
    {"Root /",
     "Корень /"},
    {"Root Motion",
     "Движение корня"},
    {"Rotate (E)",
     "Поворот (E)"},
    {"Rotation",
     "Поворот"},
    {"Roughness",
     "Шероховатость"},
    {"Row of tabs",
     "Строка вкладок"},
    {"Run the scene (it is restored on Stop)",
     "Запустить сцену (сцена будет восстановлена по Stop)"},
    {"Runs in Play mode: OnStart(entity), OnUpdate(entity, dt)",
     "Выполняется в режиме игры: OnStart(entity), OnUpdate(entity, dt)"},
    {"SAGE Engine",
     "SAGE Engine"},
    {"SAGE Engine %s",
     "SAGE Engine %s"},
    {"SAGE projects (*.sageproj)",
     "Проекты SAGE (*.sageproj)"},
    {"SAGE templates (*.sagetemplate)",
     "Шаблоны SAGE (*.sagetemplate)"},
    {"START FROM",
     "НАЧАТЬ С"},
    {"SagePlayer not found. Put it next to the editor, build the SagePlayer target, or set SAGE_PLAYER_PATH. Looked in:",
     "SagePlayer не найден. Положите его рядом с редактором, соберите цель SagePlayer или задайте SAGE_PLAYER_PATH. Искали:"},
    {"Samples / texel",
     "Выборок на тексель"},
    {"Saturation",
     "Насыщенность"},
    {"Save",
     "Сохранить"},
    {"Save Material",
     "Сохранить материал"},
    {"Save Scene",
     "Сохранить сцену"},
    {"Save Scene As",
     "Сохранить сцену как"},
    {"Save Scene As...",
     "Сохранить сцену как…"},
    {"Save UI document",
     "Сохранить документ интерфейса"},
    {"Save UI prefab",
     "Сохранить префаб интерфейса"},
    {"Save as Prefab",
     "Сохранить как префаб"},
    {"Save as prefab...",
     "Сохранить как префаб..."},
    {"Save as...",
     "Сохранить как..."},
    {"Save project as template...",
     "Сохранить проект как шаблон..."},
    {"Save to Project",
     "Сохранить в проект"},
    {"Scale",
     "Масштаб"},
    {"Scale (R)",
     "Масштаб (R)"},
    {"Scale corners down when the node is smaller than they are",
     "Ужимать углы, если узел меньше их суммы"},
    {"Scene",
     "Сцена"},
    {"Scene changed since bake — re-bake",
     "Сцена менялась после запекания — стоит перезапечь"},
    {"Scene lights",
     "Источники света сцены"},
    {"Scene object that points at a .uidoc document",
     "Объект сцены со ссылкой на документ .uidoc"},
    {"Scene: %s  |  Entities: %zu",
     "Сцена: %s  |  объектов: %zu"},
    {"Scenes (*.sage)",
     "Сцены (*.sage)"},
    {"Script",
     "Скрипт"},
    {"Script assigned: ",
     "Скрипт назначен: "},
    {"Scripts (*.lua)",
     "Скрипты (*.lua)"},
    {"Scroll target",
     "Принимает прокрутку"},
    {"Scroll view",
     "Прокрутка"},
    {"Search...",
     "Поиск…"},
    {"Section",
     "Участок"},
    {"Select",
     "Выбрать"},
    {"Select a node",
     "Выберите узел"},
    {"Select all on focus",
     "Выделять всё при фокусе"},
    {"Select an object in the viewport or Hierarchy, or a file in Assets.",
     "Выберите объект во вьюпорте или в Hierarchy, либо файл в Assets."},
    {"Selection",
     "Выбор"},
    {"Settings saved: sage.cfg",
     "Настройки сохранены: sage.cfg"},
    {"Shaded",
     "С освещением"},
    {"Shader",
     "Шейдер"},
    {"Shader limit: %d point + %d spot lights per frame",
     "Предел шейдера: %d точечных и %d прожекторов на кадр"},
    {"Shadow",
     "Тень"},
    {"Shadow Resolution",
     "Разрешение теней"},
    {"Shadow cast inside the shape",
     "Тень, падающая внутрь фигуры"},
    {"Shadow color",
     "Цвет тени"},
    {"Shadow offset",
     "Смещение тени"},
    {"Shadow softness",
     "Мягкость тени"},
    {"Shadows",
     "Тени"},
    {"Shape",
     "Форма"},
    {"Share the current project",
     "Поделиться текущим проектом"},
    {"Shift applied after layout — for animation",
     "Сдвиг после раскладки — для анимации"},
    {"Shininess",
     "Блеск"},
    {"Show Grid",
     "Показать сетку"},
    {"Show all",
     "Показать всё"},
    {"Show anchors",
     "Показывать якоря"},
    {"Show bounds",
     "Показывать границы"},
    {"Show clip regions",
     "Показывать области обрезки"},
    {"Show everything",
     "Показать всё"},
    {"Show hit areas",
     "Показывать области попадания"},
    {"Show layers",
     "Показывать слои"},
    {"Show masks",
     "Показывать маски"},
    {"Show outside",
     "Не обрезать"},
    {"Show pivots",
     "Показывать опорные точки"},
    {"Show render batches",
     "Показывать батчи"},
    {"Show the sun",
     "Показать солнце"},
    {"Shows a value",
     "Показывает значение"},
    {"Shrink corners",
     "Ужимать углы"},
    {"Side",
     "Сбоку"},
    {"Sides",
     "Сторон"},
    {"Single view",
     "Один вид"},
    {"Size",
     "Размер"},
    {"Size: %llu bytes",
     "Размер: %llu байт"},
    {"Sizes are scaled by the entity's Transform scale",
     "Размеры домножаются на масштаб из Transform объекта"},
    {"Sizing",
     "Размеры"},
    {"Skew",
     "Наклон"},
    {"Sky",
     "Небо"},
    {"Sky Horizon",
     "Небо у горизонта"},
    {"Sky Top",
     "Небо в зените"},
    {"Sky tints upward faces, Ground — downward",
     "Sky красит грани, смотрящие вверх, Ground — вниз"},
    {"Skybox",
     "Небо"},
    {"Slice scale",
     "Масштаб девятины"},
    {"Slider",
     "Ползунок"},
    {"Smoothing",
     "Сглаживание"},
    {"Snap step for the current mode.\nWhen building from blocks, set it to the block size.",
     "Шаг привязки для текущего режима.\nДля постройки из блоков ставьте его равным размеру блока."},
    {"Snap to grid",
     "Притягивать к сетке"},
    {"Snap to step",
     "Привязка к шагу"},
    {"Snapping and its step",
     "Привязка и её шаг"},
    {"Soft edge width in pixels",
     "Ширина мягкого края в пикселях"},
    {"Soft shadow under the node",
     "Мягкая тень под узлом"},
    {"Softness",
     "Мягкость"},
    {"Sort Order",
     "Порядок"},
    {"Source",
     "Источник"},
    {"Source rect",
     "Кусок исходника"},
    {"Spacing along the main and cross axes",
     "Зазор вдоль основной и поперечной осей"},
    {"Speed",
     "Скорость"},
    {"Sphere",
     "Сфера"},
    {"Spin",
     "Вращение"},
    {"Spot",
     "Прожектор"},
    {"Spread",
     "Разрастание"},
    {"Sprite",
     "Спрайт"},
    {"Stack",
     "Стопка"},
    {"Stack offset",
     "Сдвиг стопки"},
    {"Stars",
     "Звёзды"},
    {"Start",
     "Старт"},
    {"Start Color",
     "Начальный цвет"},
    {"Start angle",
     "Начальный угол"},
    {"Start from",
     "Начать с"},
    {"Startup folder",
     "Папка запуска"},
    {"Static",
     "Статическое"},
    {"Static occluder for baked GI; lightmapped = has own lightmap",
     "Статичный перекрыватель для запечённого GI; «с лайтмапой» — есть своя карта освещения"},
    {"Steeper than this and the character slides",
     "Круче — персонаж соскальзывает"},
    {"Step",
     "Шаг"},
    {"Step Height",
     "Высота ступеньки"},
    {"Steps decide banding, accumulation decides grain, scale decides sharpness. Turn accumulation off and the same number of steps becomes visibly noisy.",
     "Шаги решают полосы, накопление — зерно, масштаб — резкость. Выключите накопление, и то же число шагов станет заметно зернистым."},
    {"Stop",
     "Стоп"},
    {"Stop and restore the scene",
     "Остановить и вернуть сцену как была"},
    {"Strength",
     "Сила"},
    {"Style",
     "Стиль"},
    {"Style name",
     "Имя стиля"},
    {"Subsystems: %zu (all v1)",
     "Подсистемы: %zu (все v1)"},
    {"Subtree from a reusable file plus this instance's differences",
     "Поддерево из общего файла плюс отличия этого экземпляра"},
    {"Sun",
     "Солнце"},
    {"Sun and moon in the sky",
     "Солнце и луна на небе"},
    {"Sun disc along the sun direction, moon opposite it,\nstars appear as the sun goes below the horizon.",
     "Диск солнца по направлению Sun Direction, луна противоходом,\nзвёзды проступают, когда солнце уходит за горизонт."},
    {"Sun of the scene",
     "Солнце сцены"},
    {"Supported:",
     "Поддерживаются:"},
    {"Surface Offset",
     "Отступ от поверхности"},
    {"Sweep angle",
     "Угол дуги"},
    {"Tab index",
     "Порядок табуляции"},
    {"Tabs",
     "Вкладки"},
    {"Target (world)",
     "Цель (в мире)"},
    {"Target Id (-1 = world)",
     "Номер цели (-1 — мир)"},
    {"Template installed:",
     "Шаблон установлен:"},
    {"Template removed:",
     "Шаблон удалён:"},
    {"Template written:",
     "Шаблон записан:"},
    {"Temporal Accumulation",
     "Накопление по кадрам"},
    {"Temporal Blend",
     "Доля истории"},
    {"Texel Scale",
     "Масштаб текселя"},
    {"Texels / unit",
     "Текселей на единицу"},
    {"Text",
     "Текст"},
    {"Text field",
     "Поле ввода"},
    {"Texture",
     "Текстура"},
    {"Texture 0",
     "Текстура 0"},
    {"Texture 1",
     "Текстура 1"},
    {"Texture 2",
     "Текстура 2"},
    {"Texture 3",
     "Текстура 3"},
    {"Texture offset",
     "Смещение текстуры"},
    {"Texture or sprite",
     "Картинка или спрайт"},
    {"Texture scale",
     "Масштаб текстуры"},
    {"Texture, sprite or nine-slice",
     "Картинка, спрайт или девятина"},
    {"Texture: ",
     "Текстура: "},
    {"Textures",
     "Текстуры"},
    {"That folder already exists and is not empty",
     "Такая папка уже есть и не пуста"},
    {"The built game will not find it. Bring it into the project:",
     "В собранной игре не найдётся. Внесите его в проект:"},
    {"The cone shines along the object's forward (-Z of its rotation). Its shadow is a separate map in the atlas: there are few, and they go to the brightest sources.",
     "Конус светит вдоль «вперёд» объекта (-Z поворота). Тень — отдельная карта в атласе: их немного, и достаются они самым ярким источникам."},
    {"The editor did not close normally last time. Below is the full report written at that moment — it is what a developer needs to find the cause.",
     "В прошлый раз редактор закрылся не сам. Ниже — полный отчёт, записанный в тот момент: именно он нужен разработчику, чтобы найти причину."},
    {"The engine's own format: loads without parsing and weighs less.\nThe source file stays where it is.",
     "Свой формат движка: грузится без разбора и весит меньше.\nИсходный файл остаётся на месте."},
    {"The file is gone or damaged — details in the console.",
     "Файл удалён или повреждён — подробности в консоли."},
    {"The file is missing. Put it back or reassign the asset —\nonly the .meta sidecar could have caught a rename made outside the editor.",
     "Файла нет. Верните его на место или переназначьте ассет —\nпереименование мимо редактора мог поймать только сайдкар .meta."},
    {"The filter matched nothing",
     "Ничего не найдено по фильтру"},
    {"The folder already contains ",
     "В папке уже есть "},
    {"The folder is not accessible: ",
     "Папка недоступна: "},
    {"The look comes from the material. Turn the switch on only to make THIS object differ from others sharing the same material.",
     "Вид берётся из материала. Включайте переключатель, только чтобы ЭТОТ объект отличался от других с тем же материалом."},
    {"The look of an object is defined by its material.",
     "Вид объекта задаёт материал."},
    {"The look of the scene's world: sky, air, ambient light. Saved with the scene. Light SOURCES are objects — see the hierarchy. Quality and cost are in Game Settings.",
     "Как выглядит мир сцены: небо, воздух, окружающий свет. Хранится в сцене. Сами ИСТОЧНИКИ света — объекты, они в иерархии. Качество и цена кадра — в настройках игры."},
    {"The model failed to load: ",
     "Модель не загрузилась: "},
    {"The most expensive pass of the frame: light in the air and\nvolumetric clouds. Visible in the viewport and in the Game\npanel exactly as in the built game.",
     "Самый дорогой проход кадра: свет в воздухе и объёмные\nоблака. Виден во вьюпорте и в панели Game ровно так же,\nкак в собранной игре."},
    {"The name cannot be empty",
     "Имя не может быть пустым"},
    {"The name reaches the object's script as OnMessage(entity,\nname, data) — the same path SendMessage uses.",
     "Имя придёт в скрипт объекта как OnMessage(entity, name,\ndata) — тем же путём, что и SendMessage."},
    {"The prefab could not be placed: ",
     "Префаб не поставился: "},
    {"The previous session seems to have crashed",
     "Похоже, прошлый запуск завершился аварийно"},
    {"The properties of this entity belong to it alone.",
     "Свойства этой сущности — только её."},
    {"The server sends this object to clients; they follow it",
     "Сервер рассылает этот объект клиентам, они повторяют его движение"},
    {"The sky or its celestials are off — see Environment.",
     "Небо или его светила выключены — см. окно «Среда»."},
    {"The sun's disc, direction and colour are on the sun object — select it in the hierarchy.",
     "Диск солнца, его направление и цвет — на самом объекте-солнце: выберите его в иерархии."},
    {"Theme changed",
     "Оформление изменено"},
    {"Theme saved:",
     "Тема записана:"},
    {"Theme:",
     "Оформление:"},
    {"There are unsaved changes (Ctrl+S)",
     "Есть несохранённые правки (Ctrl+S)"},
    {"There is no editor for this file type.",
     "Для этого типа файла редактора нет."},
    {"There is no surface under the selection",
     "Под выделенным нет поверхности"},
    {"Thickness",
     "Толщина"},
    {"This cannot be undone.",
     "Это действие необратимо."},
    {"This file cannot be applied to an object",
     "Этот файл нельзя применить к объекту"},
    {"This file cannot be assigned to an object",
     "Этот файл на объект не назначается"},
    {"This folder is empty.",
     "Папка пуста."},
    {"This light IS the sun: it casts the cascaded shadows and it is where the procedural sky draws its disc. Point it by rotating the object, or by azimuth and elevation below.",
     "Этот свет и есть солнце: он отбрасывает каскадные тени, и по нему процедурное небо рисует диск. Направляют его поворотом объекта или азимутом и высотой ниже."},
    {"This scene is not from this project — assets may not be found",
     "Сцена не из этого проекта — ассеты могут не найтись"},
    {"This template is not installed next to the editor",
     "Этот шаблон не установлен рядом с редактором"},
    {"This template is not installed next to the editor:",
     "Этот шаблон не установлен рядом с редактором:"},
    {"Three numbers",
     "Три числа"},
    {"Timestamps are not ready yet — wait a few frames.",
     "Метки ещё не созрели — подождите несколько кадров."},
    {"Tint",
     "Тон"},
    {"Tint, brightness, contrast, saturation",
     "Подкраска, яркость, контраст, насыщенность"},
    {"Toggle",
     "Переключатель"},
    {"Tooltip",
     "Подсказка"},
    {"Tooltip key",
     "Ключ подсказки"},
    {"Top",
     "Сверху"},
    {"Top-left, top-right, bottom-right, bottom-left",
     "Левый верхний, правый верхний, правый нижний, левый нижний"},
    {"Track color",
     "Цвет дорожки"},
    {"Transform",
     "Преобразование"},
    {"Translate",
     "Сдвиг"},
    {"Transparency",
     "Прозрачность"},
    {"Triangles",
     "Треугольников"},
    {"Triangles: %d, bounds %.2f x %.2f x %.2f",
     "Треугольников: %d, габарит %.2f x %.2f x %.2f"},
    {"Turn on",
     "Включить"},
    {"Two columns",
     "Два столбца"},
    {"Two numbers",
     "Два числа"},
    {"Type",
     "Тип"},
    {"Typography with its own layout pass",
     "Типографика со своим проходом раскладки"},
    {"UI Document",
     "Документ интерфейса"},
    {"UI document loaded",
     "Документ интерфейса загружен"},
    {"UI document saved",
     "Документ интерфейса сохранён"},
    {"UI documents (*.uidoc)",
     "Документы интерфейса (*.uidoc)"},
    {"UI prefab saved",
     "Префаб интерфейса сохранён"},
    {"UV rect",
     "Область UV"},
    {"Ultra",
     "Максимальные"},
    {"Undo",
     "Отменить"},
    {"Units per second; zero snaps instantly",
     "Единиц в секунду; ноль — мгновенно"},
    {"Unknown component",
     "Неизвестный компонент"},
    {"Unpack prefab",
     "Разорвать связь с префабом"},
    {"Unparent",
     "Отвязать от родителя"},
    {"Up",
     "Вверх"},
    {"Use Limits",
     "Ограничения"},
    {"Use Pole",
     "Использовать направляющую"},
    {"VSync",
     "Вертикальная синхронизация"},
    {"Value",
     "Значение"},
    {"Variables",
     "Переменные"},
    {"Variant",
     "Вариант"},
    {"Vector icon drawn by the engine, not a file",
     "Векторный значок, который движок рисует сам, а не загружает"},
    {"Vertex",
     "Вершинный"},
    {"Vertical",
     "По вертикали"},
    {"Vertical align",
     "Выравнивание по вертикали"},
    {"Vertical layout container",
     "Контейнер вертикальной раскладки"},
    {"View",
     "Обзор"},
    {"View layout and projection",
     "Раскладка видов и проекция"},
    {"Viewport",
     "Вьюпорт"},
    {"Viewport grid",
     "Сетка вьюпорта"},
    {"Viewport, content size and offset — nothing about the content",
     "Окно, размер содержимого и смещение — и ничего о самом содержимом"},
    {"Views",
     "Виды"},
    {"Vignette",
     "Виньетка"},
    {"Visible",
     "Видимый"},
    {"Volumetric Intensity",
     "Сила рассеяния"},
    {"Volumetric Light",
     "Объёмный свет"},
    {"Volumetric Light...",
     "Объёмный свет..."},
    {"Volumetric Scale",
     "Разрешение прохода"},
    {"Volumetric light and clouds are a frame cost, not a scene property — they live in the engine settings.",
     "Объёмный свет и облака — цена кадра, а не свойство сцены: они в настройках движка."},
    {"Volumetrics",
     "Объёмный свет"},
    {"Warn (%d)",
     "Предупр. (%d)"},
    {"Weight",
     "Вес"},
    {"What to show in the toolbar",
     "Что показывать в строке инструментов"},
    {"When",
     "Когда"},
    {"Where it glows and where it does not. Multiplied by the emissive colour and strength.",
     "Где светится, а где нет. Умножается на цвет и силу свечения."},
    {"Where templates live",
     "Где лежат шаблоны"},
    {"Where the node sits inside its parent",
     "Где узел стоит внутри родителя"},
    {"Where to build the game",
     "Куда собрать игру"},
    {"Where to create the project",
     "Куда создать проект"},
    {"Where to put the project",
     "Куда положить проект"},
    {"Where to save the material",
     "Куда сохранить материал"},
    {"Where to write the template",
     "Куда записать шаблон"},
    {"Whether a pass runs at all and at what resolution. Which light casts those shadows is a property of the light object.",
     "Выполняется ли проход вообще и в каком разрешении. А какой источник отбрасывает тени — свойство самого объекта-света."},
    {"Whole number",
     "Целое число"},
    {"Why is it here?",
     "Почему так?"},
    {"Width",
     "Ширина"},
    {"Width mode",
     "Режим ширины"},
    {"Will create:",
     "Будет создано:"},
    {"Will select: %s",
     "Будет выбрана: %s"},
    {"Window",
     "Окно"},
    {"Window settings apply when the game starts.",
     "Оконные параметры применяются при запуске игры."},
    {"Windowed",
     "В окне"},
    {"Windows menu returns any panel, or restore the default layout.",
     "Любую панель вернёт меню «Окна», а раскладку по умолчанию — «Сбросить раскладку»."},
    {"Wireframe",
     "Каркас"},
    {"Wrap",
     "Перенос строк"},
    {"Yes / no",
     "Да / нет"},
    {"You can bring the question back in Window -> Settings.",
     "Вернуть вопрос можно в Window -> Settings."},
    {"You can drop a model, a prefab or a material into the scene",
     "В сцену можно бросить модель, префаб или материал"},
    {"Zero derives the cell from the container",
     "Ноль — ячейка считается из контейнера"},
    {"Zero fills the shape; above zero draws an outline",
     "Ноль — заливка; больше нуля — обводка"},
    {"Zero fits the shorter side of the node",
     "Ноль — вписать в меньшую сторону узла"},
    {"Zero means continuous",
     "Ноль — плавно"},
    {"Zero means no limit",
     "Ноль — без предела"},
    {"Zero means unlimited",
     "Ноль — без ограничения"},
    {"[%s] %s  (x%d)",
     "[%s] %s  (x%d)"},
    {"always",
     "всегда"},
    {"and are edited right here.",
     "правятся здесь же."},
    {"batches",
     "батчей"},
    {"bone not found in skeleton",
     "кость в скелете не найдена"},
    {"bytes",
     "Б"},
    {"cross-fading %.0f%%",
     "переход %.0f%%"},
    {"curl not found — downloading is unavailable. Templates can still be installed from a .sagetemplate file on the «From disk» tab.",
     "curl не найден — скачивание недоступно. Шаблон можно поставить файлом .sagetemplate на вкладке «С диска»."},
    {"error",
     "ошибка"},
    {"errors",
     "ошибки"},
    {"errors (many)",
     "ошибок"},
    {"file",
     "файл"},
    {"for example: game.start",
     "например: game.start"},
    {"just now",
     "только что"},
    {"material",
     "материал"},
    {"model",
     "модель"},
    {"no",
     "нет"},
    {"nodes",
     "узлов"},
    {"not installed",
     "не установлен"},
    {"nothing selected",
     "ничего не выбрано"},
    {"part",
     "часть"},
    {"prefab",
     "префаб"},
    {"scene",
     "сцена"},
    {"scene object",
     "объект сцены"},
    {"script",
     "скрипт"},
    {"sound",
     "звук"},
    {"t = %.2f s",
     "t = %.2f с"},
    {"targets",
     "целей"},
    {"texture",
     "текстура"},
    {"volume (dynamic); direct light stays realtime",
     "объём проб (для динамики); прямой свет остаётся реального времени"},
    {"warning",
     "предупреждение"},
    {"warnings",
     "предупреждения"},
    {"warnings (many)",
     "предупреждений"},
    {"yes",
     "да"},
    {"yesterday",
     "вчера"},
    {"| GPU %.2f ms",
     "| GPU %.2f мс"},
    {"| lines: %d | %s",
     "| строк: %d | %s"},
    {"| no GPU timers",
     "| таймеров GPU нет"},
};
