// СГЕНЕРИРОВАНО sage_icon_builder.py — НЕ ПРАВИТЬ РУКАМИ.
// Источник: engine/icons/icons.json + engine/icons/tabler/*.svg
// Пересобрать: python3 scripts/sage_icon_builder.py
#pragma once
#include <cstdint>

namespace sage::ui::icons {

// Значки перечислением, а не строкой: опечатка в имени обязана быть
// ошибкой компиляции, а поиск значка — сложением адреса, а не поиском
// по таблице строк (§9 ТЗ).
enum class Icon : uint16_t {
    Play,
    Pause,
    Stop,
    Step,
    New,
    Open,
    Save,
    Undo,
    Redo,
    Cut,
    Copy,
    Paste,
    Delete,
    Rename,
    Folder,
    FolderOpen,
    File,
    FileCode,
    Package,
    Import,
    Export,
    Search,
    Filter,
    Refresh,
    Settings,
    Adjustments,
    Menu,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    ChevronLeft,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    Close,
    Check,
    Plus,
    Minus,
    Dots,
    DotsVertical,
    Eye,
    EyeOff,
    Lock,
    LockOpen,
    Pin,
    Star,
    Bookmark,
    Info,
    Warning,
    Error,
    Bug,
    Help,
    Camera,
    Light,
    Sun,
    Moon,
    Bolt,
    Flame,
    Droplet,
    Cube,
    Sphere,
    Cylinder,
    Plane,
    Mesh,
    Terrain,
    Material,
    Texture,
    Shader,
    Script,
    Audio,
    Particles,
    Physics,
    Bone,
    Animation,
    Timeline,
    Keyframe,
    Move,
    Rotate,
    Scale,
    Select,
    Hand,
    Zoom,
    Grid,
    Perspective,
    Wireframe,
    Shaded,
    Snap,
    Hierarchy,
    Assets,
    Console,
    Profiler,
    Layers,
    Prefab,
    Component,
    Window,
    Theme,
    Link,
    Unlink,
    Anchor,
    Text,
    Image,
    Button,
    Slider,
    Checkbox,
    Input,
    Panel,
    Dock,
    Tab,
    Plugin,
    Terminal,
    Code,
    Home,
    Build,
    Keyboard,
    Network,
    World,
    Target,
    Ruler,
    Eraser,
    Brush,
    Wand,
    Crop,
    Split,
    Rows,
    Maximize,
    Minimize,
    Count,
};

inline constexpr int kIconCount = 127;
inline constexpr int kAtlasCount = 3;
inline constexpr int kAtlasSizes[kAtlasCount] = {16, 20, 24};

} // namespace sage::ui::icons
